update changelog for 1 . 1 . 1
update changelog for 1 . 1 . 1
missing icon
TFJ - 266 fixed test . properties
Added missing JNA jar
Adds lintOptions to Library .
Upgrade to Reflections 0 . 9 . 9 - RC2
Updated JavaApplicationStub , which runs both on Leopard and Tiger .
set IDEA JDK from build script
Fix build .
Add missing JSON highlighting to example .
prepare for next development iteration
correct a typo in a comment
Resolve bower dependency conflict , hang ( zeppelin - web )
Ignore project icons
Added files via upload
Add Eclipse 4 . 5 new workspace folder to .
removed unnecessary import
Added the reduce function to the manual
Set the correct version
Remove circleci config
removing dangling directory
Add link to documentation about the Polymer pass .
Restored @ since javadoc tag of Convertible
Added idea project files to git ignored files
Adding issue template
add a blank line to try and test github webhook
Added tmp / to .
Ignore testng output
Eradicate whitelisting
Updated changelog for 5 . 5 . 3 .
Removed DS_Store files
prepare for next development iteration
bumped elasticsearch api version
Fix typo .
add the mavencentral repository on the root level
do not use the lastest tool on travis
added few known transitive verbs .
updated documentation in alpha rather than random order
Updated notification icon for Android 2 .
Change xml tags order .
replace new jar
still need a res dir to prevent eclipse from freaking out
remove specify developer team
Disable clip to padding for row items to avoid clipped transition animation
update changelog for 0 . 9 . 0 - rc1 , prep for rc2
Changes support library reference to v21 . 0 . 3 .
Begin development of 1 . 11 .
Ignore tests in release perform as they ' re already run in the prepare stage
updated file
Add maven central repo to readme
remove mail notifications ( for now ) from travis
remove debug line
remove PIDFILE at stop time
Add building buck completed line
Only run findbugs for main
build config fix
Set the correct version
Fix build issues
Add CHANGELOG . md
upload demo gifs
automatically create outputDirectory
add overlay
When closing the stream for the host ' s web . xml if an exception occur then hostTimeStamp must be set to - 1 and not the globalTimeStamp .
Updating parent pom version of reporting to 1 . 3 . 0
Add screenshots
Adding empty file
add ignore for jre . tgz on linux
Added files via upload
Fixing GLIBC 2 . 4 problem on Debian system .
Added tag 0 . 0 . 7 . 8 for changeset 9bb7ad84eace
Fix log version string .
update changelog for 0 . 9 . 0 - rc1 , prep for rc2
Suppress warning
Fixed method layout in ActivityApp
Turn off baseline aligment in wide show info layout .
added newline .
Updated version
Fix compile warning
prepare for next development iteration
Prepare change log .
fix travis config
added few known transitive verbs .
Build fix
Skip deployment of integration - tests
Require Maven 3 . 0 .
Remove mavenLocal ( ) from buildSrc
update changelog for 1 . 1 . 1
keep deprecated requestFBOLayer ( ) method for now .
remove old
Appease the checkstyle overlords .
added few known transitive verbs .
add eclipse and idea projects to gitignore
Added docs for the docs .
testing out travis as ci
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
added Travis CI configuration .
Added travis - ci
Add shell script for zan
Fix for issue 27
Fix travis
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
update parent pom
disable tests to obtain a cache
Increment gradle build tools
Create README . md
Eradicate whitelisting
update changelog for 1 . 1 . 1
Updated gradle release plugin dependency to 0 . 1
add jar
Bump pegasus version to 1 . 8 . 5
corrects tests for GROOVY - 2774
Removed unnecessary asset
remove todo
so release local reference
started core project
Update doc commit pointer for 0 . 3 . 2 release
Only use jdk8 in travis
removed empty statement
help ID ( IDEADEV - 34211 )
Updated CHANGES . txt
make build . sh executable
remove bin directory
moving version to 1 . 3 . 0 due to more major changes
Fix broken test by adding relative ordering to resources2 . jar so it is processed after resources . jar
UNKONWN
Setting default name for multi - project
starting 0 . 5 . 4 - SNAPSHOT
LPS - 22149 - This will lockup the browser
Updated dependency version to latest release
bump to version 1 . 2 . 1
Fix build .
Doubles the height of chunks ( once again ) .
Add glyphs for Vertical Text
Remove unused file
gh - 471 - updated travis script
Prepare next development version .
updated CHANGES
Don ' t build aggregated source jar .
added info option to travis to output more information
Remove oraclejdk7 from travis .
Add Eclipse files to .
Add Eclipse files to .
rename unit - tests execution to default - test
Remove ntlm module from pom
Add Application class .
Delete android - support - v4 .
Added a release_description file to be used by CI
Modify changelog
force 3 jvms even if multi - machine
add table of contents in python / README
Reorder modules in top - level pom . xml
Should fix black laser beams .
Added gitignore .
Updated demo art
added checkstyle file info
set the version
add jdk
Added Example apk
Remove debug statement
Fix crash bug when click capture button after set a filter
add gitignore
remove old screenshots they are not representativ anymore
Removing unused imports .
Fix build .
Added tag 0 . 0 . 7 . 2 for changeset 5de91e5a0e95
update changelog for 1 . 1 . 1
update changelog for 1 . 1 . 1
Prepare change log .
Add commons - collections jar .
we could be leaking file descriptors here
activated " testIteratingWithList " test
Ignore IDEA directory
suppress warning
regenerate gradle - wrapper . jar using 1 . 10
typo , removed sys accidently a couple days back
regenerate gradle - wrapper . jar with 1 . 9 - rc - 4
more on greenify some plugin . xmls
Included string . h to use memset in stress . cpp
removed the lcrypto BouncyCastle lightweight crypto library , since the source is now part of the project directly as info . guardianproject . bouncycastle
Updated the gitignore file to ignore eclips config files .
add bin to gitignore
Added tag 0 . 0 . 7 . 2 for changeset 5de91e5a0e95
Make gradle wrappers executable
Adding bin related files to gitignore ( # 130 )
update Universal - Image - Loader
Changed version
updated sonatype parent pom version from 7 to 9
Add icon # 1416
improved handling for Droid Incredible 2
Reseting a project . properties file
update refs
Set version to be 1 . 0 . 1 SNAPSHOT rather than 1 . 1 .
Removed old symbol pattern .
Add maven central repo to readme
correct null + String to not throw an NPE
Added app icon for xhdpi
Appease the checkstyle overlords .
Updated travis config
Get me out the stupid readme file .
bump to version 1 . 5 . 2
Reduce the amount of logging from the Javadoc plugin .
can ' t access static field from nested closures
Add toString ( ) to IndexShardGateway
Fix typo which cause stack overflow if children ( ) was called
Remove a spurious symlink
Added reference to distribution .
Create grade files to appease NetBeans plugin
Add support lib to Sample project
follow / unfollow API
set IDEA JDK from build script
add iframe option
Ignore OSX and IDE files
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Build the JNI lib as a dependency rather than packaged
reduce T * Map , T * List memory consumption for empty collections ; just like ArrayList did in JDK8
Updated build . gradle for maven
Fix build errors with m2e
Updating samples
Make notest .
create docs directory
Added screenshot
added coverage to test interfaces
Add commons - collections jar .
comment out snapshot plugin for release
Use new sanitizer option .
Suppress warning
updated studio
Update stack diagram .
Make privacy provider single user for multi - user environments
removing stuff useless for release
Prepare next release v1 . 0 . 2 - SNAPSHOT
Add org . jetbrains . android as dependency
Add gitignore file , clean Broadcaster internals when invoking destroy
Fixed import .
Add * .
remove mongo . jar and bson . jar on clean .
upload demo gifs
Fix possible NPE on response recycle .
Move QueueFile to ' io ' package .
rename code style jar
added favicon
Remove the background from the RelativeLayout , allowing the ActionBar style background to show through
Added support for using a transaction to perform batch tasks .
Updated pom
Created PopularMoviesView
change the default release scope to be patch
add missing import
Ignore project configuration files for NetBeans
Prepare next version ( 0 . 3 )
updated credits
added changelog for 1 . 6 . 1
UNKONWN
UNKONWN
Upgraded Wrapper
prepare release storm - hbase - 0 . 1 . 2
Should fix black laser beams .
run tests in build
Permit the folder list item to expand vertically .
Updated notification icon for Android 2 .
Add project_config to sdk module
Remove unused file
bump to version 1 . 5 . 2
Upgraded maven - release - plugin to version 2 . 1 .
Replace menu title image
Updated build . gradle to buildToolsVersion " 21 . 1 . 1 "
add unique to python
Ignore Eclipse project files .
removed erroneous tab character
add readme
update changelog for 1 . 1 . 1
update osx natives
bump version for 0 . 9 . 0 release
update changelog for 1 . 1 . 1
Added the legend to the bottom of the graph .
Move the Swing Model test to swing module as well
Ninja fix CommitLogStressTest . testRandomSize
update doc
Fix markdown rendering of bullets on homepage
Added checkstyle to core and cache module
Remove unused import
Add tag required by schema to Cobertura configuration .
Changed version number for release
ignore maven target folder and eclipse project files ( .
added index graph for wiki documentation .
fix build for example project
build config fix
removing empty files
Update the alias in the server side trust store to match the name used for the certificate .
Set minSdkVersion to 8 for DroidGap project
reset the tree after the branch
Removes extra padding introduced during merge from develop
set IDEA JDK from build script
use the latest networking version
Upgraded wrapper
Remove unnecessary permission from gallery app
update changelog for 1 . 1 . 1
Zeppelin Server doesn ' t catch all exceptions when launching interpreter . sh
Temporarily disable MixinC00Handshake
Bump pegasus to 1 . 9 . 5
build make buildlog include tests run and fail stacktraces
Remove ignored file
Create README . md
die extra plugins
Remove Y
ignore class files in root ( which are generated by " gradle test " )
Fix mistype
Add icon for the project
Adding a ' .
Add a README section for open items to remind me to check & test XML
Fix build
Fix build .
Skip javadoc
Added getContext to FakeDialog
Add steam output to .
Add select image from album for upload module .
Add more eclipse project configuration
Add javadoc plugin
Test travis CI .
update changelog for 1 . 1 . 1
Added files via upload
Fix mCoveredFadeColor setter
Add final newline to editorconfig .
remove debug line
do not show gpx export items at start
Ok , so we need this .
Don ' t run connectedCheck
Fix OF - 654 - Limit index size of JID to 256 for mysql
prepare for next development iteration
Renamed test process to make the test run on case sensitive operating systems
Fixed import .
Fix build
Add test - reports / to gitignore
Bumped up parent pom version to solve custom checkstyle issue
remove unused method
adding jna for native library access
Added cobertura plugin
Add Small ignore files
Add specific xcode sdk to travis . yml
Travis does not support a JDK named ' openjdk8 '
Ignore my TODO list
Added package custom
Remove image sample
remove swp file
Permit the folder list item to expand vertically .
Added person .
Removed some unnecessory code
Add icon for the project
Remove NOPASS .
upload demo gifs
add icon
Fix broken build
add change
Have a bottom actionbar in the Search activity to be consistent .
Skip the enforcer plugin in the examples
Fix a rare NPE crash in Android 2 .
Added StatefulPersistenceContext . getProxiesByKey ( ) ( needed for testing non - flushed changes )
upload demo gifs
updated documentation in alpha rather than random order
Move the wcursor increment after the assert
add bin to gitignore
Make text in table wrappable
Changed Travis cfg
update refs
UNKONWN
Add vcs root
Fix permissions
Create README - ZH .
Remove temporary test
do not show gpx export items at start
improved handling for Droid Incredible 2
Added check for invalid scope
Inflate my ego ( add Aphoh to the contributors list in README . md
add " cpp " target to build OTF decoder and OTF decoder doc
ignore * .
Removed unused resurce
remove unused logger
Added screenshot
update thrift jar to current recommended revision
added bnd jar so that we can generate osgi manifest using bnd from our ant file
update idea 128x128 win icons
added index graph for wiki documentation .
Add caching of Maven artifacts to Travis CI build
Tweak gitignore .
Updated build . gradle for maven
Log test errors .
Add intellj project files to .
Remove unused file
Fix typo
remove warning
added idea ignore config
do not show gpx export items at start
Added files via upload
Removed extra latch countdown that can caused non deterministic test failures
Fix IndexOutOfBoundsException setSpan happening on Samsung devices by simply disabling long click events on edittext .
Adding binary dependencies for aapt
Fix build .
Fix build
Change Sorbian ISO 639 - 2 from wen to hsb
Don ' t delete jars
add deprecated application . properties to skeleton
Ignore gradle related files .
update refs
LPS - 48133 update SDK
Removed Merriweather light variation assets ( since they won ' t be used )
add antlr - 3 . 1 . 3 ( should have been in r761805
Add missing LOCAL_MIN_SDK_VERSION for Support Library demos
Pushed CUnit back to 1 . 12
Remove the superfluous ProGuard rule for the database package
Updated screenshot
Prepare change log .
Add more eclipse project configuration
Added high res launcher icons for xhdpi and xxhdpi .
Delete default README
Update SpongeCommon for DestructEntityEvent cause improvements .
LPS - 63269 apply patch
update osx / darwin native
Upgrade rxnetty version to 0 . 3 . 13
Removed javadoc dependency from javadocJar method to avoid automatic javadoc build
added getNotificationUri to comply with API level 19
bump socket . io
Fix a MethodSelectionException for Java 8 ( # 421 )
UNKONWN
Remove redundant openjdk7 , non - existing openjdk8 from Travis - CI config
Add getOnFocusChangeListener to View
Prepare change log .
Guarding moved pass CheckRegExp with skipNonTranspilationPasses flag .
just added author tag
Added public method to Cache to check initialized state
updated pom . xml to use graphdb - deps - all - 0 . 3 .
Set VERSION to 5 . 3 . 0 - dev ( via coho )
do not show gpx export items at start
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
add eclipse and idea projects to gitignore
Updated Ant jar
Add forgotten static file robots . txt
bump to 1 . 7 . 6 and minor CHANGELOG cleanup
Fix build .
Remove unused var
update travis . yml
change wl12xx hotspot ssid to spike
prepare for next development iteration
add maven support
update Universal - Image - Loader
included default .
Add contentDescription for compact action_mode_close_item
UNKONWN
CHanged target build sdk for osmand
ignore files
bump maven - resources - plugin to 3 . 0 . 2
fix wrong name
Remove unnecessary code
added ForbidAnnotationElementValueCheck
updated apk
use the latest 0 . 10 . 103 version
Add maven central repo to readme
bumped min maven version to 3 . 2 . 1
Remove unused import
UNKONWN
Remove unnecessary code
Ignore project configuration files for NetBeans
updated CHANGES
Add slack integration for travis
rename file so its title has a space in it
remove unnecessary semicolon
Fix build .
removed package statement as we ' ve stuff in groovy .
comment out snapshot plugin for release
disable tests to obtain a cache
remove deprecated @ S3method roxygen2 completion
Fix null top view crash
Prepare next release
make start . sh executable
Add support library , to be used for ViewPagers
Add * .
update com . android . tools . build to 0 . 4 .
bump version for 0 . 9 . 0 release
Add CodeNarc rule exclusion
do not show gpx export items at start
delete junk
Added Makefile for R .
updated fake - dom with functions for ComputedStyle
Pass the - - porcelain flag to git status .
Add xxxhdpi drawables
UNKONWN
add getCount method to BytesInputStream ( @ MysteryMachine )
Fix build .
Set isInEditMode ( ) to true # 9
bumped version
add toString ( ) to GoLightType
revert change on whereCond name
set IDEA JDK from build script
Set source and target compatibility to Java 1 . 7 .
Fixed validate IPv4 address method
Fix broken image
Make 1 . 0 . 0 header the same level as others ( # 2885 )
Added missing script line
Add gradlew . bat to .
Fixed invalid jdk range in pom
Added failing test for JSON output
Use Travis - CI ' s container based infra
updated min sdk to 11
Added docs for IDE / plug - in
Updated CHANGES . txt
update emitter version
Remove unnecessary code
update travis
update changelog for 0 . 9 . 0 - rc1 , prep for rc2
Bump common ref .
Call super . onDestroy ( )
Remove extra newline
Add a note about changes .
Delete default README
prepare release HikariCP - 1 . 3 . 7
Adding binary folder and .
Fixed case of SideBitFlag
Updated structdb
updating cacheword
updated version
Setting build group and version
add res directory .
adding gitignore file
Fixed version .
Add Eclipse files to .
Added person .
Fixing special handling of presence type in the model
comment out snapshot plugin for release
Should fix black laser beams .
trim some fat
Update build tools to 21 . 1 . 1 .
Fix extra right bracket
MinecraftForge / FML @ a8cbef2321a8e1bdfac56476bdfb5b306f71d38b Finally hopefully fully kills the race condition causing a classcast on slow machines .
Fix log version string .
add function with zero arguments
added latest jar
Temporaly remove yahoo tests
Updated build tools and sdk
Removed un - used p . paused ( ) .
LPS - 18065 Fix bad regen
updated min sdk to 11
Add Eclipse ' s bin / folder to .
Missing mavenCentral ( ) repository
Fix typo
add change
Add Q3 2011 ADL slides to docs / shareables / adl
prepare for next development iteration
return actual value of isLocal ( ) in command line args
LRDOCS - 2232 Remove unneeded property
Make 1 . 0 . 0 header the same level as others ( # 2885 )
UNKONWN
gitignore all build / directories
Revert travis change as they do not support java6 anymore
add Alireza as contributor
added brew upgrade to MacOSX build instructions to avoid boost error .
Ignore patterns
fixed max size of library slots , close # 1710
Bump pegasus to 1 . 9 . 5
suppress warning
Make 1 . 0 . 0 header the same level as others ( # 2885 )
Add project_config to sdk module
Update the ptbtokenizer test to reflect the non - americanization
Remove unnecessary code
Add toString ( ) to IndexShardGateway
Build ' client ' target with - Wno - sign - compare .
update changelog for 1 . 1 . 1
updated example yml keyStorePath - > keyStore per the new config
Added back playInBackground property in js
Fix typo
turn off active by default on tests ( # 1843 )
Release pegasus 2 . 6 . 3 .
Only build tagged versions
force AST Injected property check with staticCheckerVisitor
test patched < gant > task and AndBuilder , that respects UnknownElements
update travis
Fix Test
preparing release version
rename main file
Remove unused file
Updated binaries
Remove the over quoting .
Fix build .
Removed obsolete macros .
remove PIDFILE at stop time
Fix build
Fix test failures for CASSANDRA - 5175
adds awesome image courtesy of the internet
upToDateWhen = false
Fix build
Fix log version string .
Return this instead of null in TimeoutStream # resume
mentioned hide offline feature in the changelog
use ant to build
Override bootstrap ' s th styles .
Specify version name for subproject properties
Remove unused file
removing comm files from jre since they needn ' t be in there
Removed legacy icons in JB workaround app
added few known transitive verbs .
Removed old symbol pattern .
Create README . md
update travis settings
updating astyanax version to 2 . 0 from 2 . 0 - beta
Update build branches
Update the alias in the server side trust store to match the name used for the certificate .
Delete proguard . jar
Fix typo
build make buildlog include tests run and fail stacktraces
Prepare next development version .
adding doc file
Remove unused file
Added StatefulPersistenceContext . getProxiesByKey ( ) ( needed for testing non - flushed changes )
Build fix
bump to version 1 . 5 . 2
Added Example apk
Added empty debug buildType
Adding maven central to build
Add forgotten static file robots . txt
UNKONWN
Add config for TravisCI
add function with zero arguments
Upgrade oss - parent
we could be leaking file descriptors here
Add Travis configuration .
ignore class files in root ( which are generated by " gradle test " )
ignore examples directory for rat
Revert default behavior of " Back Key " to exiting application .
set IDEA JDK from build script
updated credits
Fix for issue 27
Set oss parent to 9
bumped version
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
Add a shouldUpdate property to nodes whose layout changed
UNKONWN
Fix changelog
Fix Travis config syntax # 255
fixed compilation error
Ignore bin and gen
Remove extraneous semicolon .
FastArray doesn ' t overwrite toString ( ) method
fix conflicting native library error message
update usage plugin
Fix build .
Fixed import .
Build fix
Fix build
Updated log4j dependency
Adding mavenLocal ( ) for local resolution
Removed PDF from what ' s deployed to the mvn repo .
LPS - 62799 Fix NullPointer in test
added Travis CI configuration .
update changelog for 1 . 1 . 1
missing method from desktop version
fixed test
fixed git ignore name
Fix NPE in PackageParser
Introduce internal ` server ` command
Delete truth jar which I forgot to delete when removing Ant support .
Changed email address for travis
update Universal - Image - Loader
Add missing method
Fix config
fixed version
config not needed aynymore
Fixed color
update Alipay and Weixin
added wiki images
Added support for automatic legend generation for Wheelchair renderer
update changelog for 1 . 1 . 1
Changed version number so I could push the new version to dist .
update screenshots
Upgrade JUnit to 4 . 12
add overlay
Widen message list chip to better match message view .
update capture gif
Create README . md
Delete default README
comment out snapshot plugin for release
prepare for next development iteration
add travis support
Add maven central repo to readme
Remove unnecessary code
LPS - 19211 Missed build . properties
upload demo gifs
Added tag 0 . 1 for changeset d04a8ef4ccb0
Remove Gradle wrapper files from .
Removed lib / .
fixed wrong project . properties
update slf4j version
Log stack traces of test failures to the console .
Fixed a subtle bug I happened to introduce last night .
correcting version to be really 1 . 8
Fix for issue 27
Added missing property for playWhenInactive .
remove empty duplicate AbstractEdge
Add microbench to the module list
Updated gradle release plugin dependency to 0 . 1
Fixed import .
Bump otto
Modified resources . arsc file to make some resources public .
Delete default README
UNKONWN
Create README . md
Make executable
add gitkeep for assets
Remove newline at end of VERSION file
add intellij * .
UNKONWN
update windows natives
Fix lib
Set travis jdk to java8
Cleanup working directory on succesful runs of the backup stress test
remove todo
update windows natives
Fix typo in reference manual
Set the correct version
Added OGNL expression object graph expression language jar
rename code style jar
added missing imports
Fix broken image
ignore " bin " directory ( created by Eclipse )
missing curly brace in ip_range aggregation example
Fixed manifest entry
Fix changelog
Added database artefacts to .
Added support for automatic legend generation for Wheelchair renderer
made publish - maven - artifacts an executable
Add missing Override decorator
Don ' t record jbosh version if bosh is not build
Fix name of java executable
updated jsr166e to the 9 . 08 . 2015 version
fixed an error in the pom . xml file
Delete build . gradle
Remove unused file
Set oss parent to 9
Fixed import .
add toString for Fields
Prepare change log .
add the mavencentral repository on the root level
Remove unused file
Remove blank lines
Removed properties
Cache the contents of .
Make log4j an optional dependency
Prepare change log .
Fix checkstyle
UNKONWN
remove todo
bump version for move to Apache incubator
add function with zero arguments
Delete a . gif
updated to ignore merge leftover files ( orig ) and ant builds
upload demo gifs
Changed version
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
update xsoup to 0 . 2 . 1 # 75
Remove references to flatfile .
Add missing method
prepare release HikariCP - 1 . 1 . 6
Fix data driven testing example in documentation
Add missing method
Use Travis - CI ' s container based infra
Set isInEditMode ( ) to true # 9
bump to 1 . 7 . 6 and minor CHANGELOG cleanup
don ' t set the application title in the library
Move file to correct dir
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
make Preconditions package private
Update SpongeCommon for DestructEntityEvent cause improvements .
Set isInEditMode ( ) to true # 9
Bump readme version
UNKONWN
Removed unnecessary return statement
Fix warning
Ignore patterns
Create README . md
added missing def
Run the tests on oraclejdk7 and openjdk6 + 7
missing return in svg ' s getCoords
bumped version
Added screenshot
comment out snapshot plugin for release
LPS - 65607 Export the concrete package .
removed unused image
Fixed validate IPv4 address method
Disable JS tests when enabling the profile dbTests
Prevent NPE in HardwareRenderer
remove analytics from alpha not enterprise
Added files via upload
Compile tests with source attribute .
Add service graphs
Refresh checkpoints
Move the wcursor increment after the assert
Testing repo replication
Fixed bullet points in README
debug mode screenshot and miniature
improved handling for Droid Incredible 2
update ver for next dev integration
Prepare next release v1 . 0 . 1 - SNAPSHOT
Exclude JMH tests from coverage reports .
Fix build
Add text editor temporary files to .
remove debug output
Fix markdown rendering of bullets on homepage
Bump the version
Renamed maven assembly to jmxtrans - all . jar .
UNKONWN
Recommend jcenter repo .
Removed the .
add table of contents in python / README
remove a print
update build tools and target api
Created the AJAX Spider help documents , added it in penetest . html and also in the indexes .
Add extension to README file .
Updated database
remove mustRunAfter in favor of an explicit call for now
Update SpongeCommon for DestructEntityEvent cause improvements .
Upgraded slf4j - api from 1 . 6 . 1 to 1 . 7 . 2
Added dash to test push
Add CLA documents
update jars
updated studio
Updated jol to 0 . 2 to resolve the slow startup problem due to heavy GC
add table of contents in python / README
prepare release storm - hbase - 0 . 1 . 2
Moved compileSdkVersion and buildToolsVersion on top level build . gradle
Properly handle empty layout in getFirstVisiblePosition ( )
implement missing method getGlobalPosition
Move the wcursor increment after the assert
Fixed import .
fixed NPE in Box . extendToEncompass , close # 1783
Added support for using a transaction to perform batch tasks .
Fix build
Create README . md
add overlay
Reordering the build repositories in the hope that this fixes the jenkins build .
update favicon
Prepare change log .
Add credentials for CI snapshot deployments .
Introduce internal ` server ` command
Remove temporary test
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
update changelog for 1 . 1 . 1
fixed license
Bumping version name and code for 2 . 6 RC 2 .
disabled failing test
update refs
Added files via upload
updated changelog for version 0 . 2 . 2
Add the isVisible ( ) getter
Prepare change log .
Fix broken image
Fix css
Updated gif
missing return in svg ' s getCoords
keep deprecated requestFBOLayer ( ) method for now .
Updated icons to better comply with Android Developer Guidelines .
Properly stop server .
Remove unnecessary code
Made text_box_light have a white background
Add a new ' pre - checkin ' target to help keep checkins clean .
Fix wasInThePast
Added manual GLProfile shutdown to make sure that no JOGL threads are
Added Data Science doc to H2O - Dev docs site ( 1st new file )
Remove unused file
Remove obsolete file
Bumped wrapper version in the build file for consistency .
added OnionKit library import
Removed @ Override annotation
Fixed missing information
Updated travis file for Java 8 & to notify me as well .
Set executable bit of gradlew
Setting build group and version
Ignore OSX and IDE files
improved handling for Droid Incredible 2
Set the correct version
updated changelog for 0 . 9 . 5
Fix typo
Remove unused link to libcutils
resolved conflicts for merge of fb2e3c8d to master
Remove unused file
Added intelliJ hidden files to gitignore
LRQA - 16067 Add list of product names into test . properties
Create README . md
Added tag 0 . 0 . 7 . 8 for changeset 9bb7ad84eace
added support for AssertStatement
bump version for nondex - maven - plugin to 1 . 1 . 1 ( # 3439 )
adjust hight
Fix syntax error
Use the latest version of Android Tools
prepare for next development iteration
Added missing JNA jar
Added files via upload
set IDEA JDK from build script
add getCount method to BytesInputStream ( @ MysteryMachine )
Set the root project name
Package adds a newline now .
Added diffutils library
Update doc commit pointer for 0 . 3 . 2 release
bumped version
added TODO
add an accessor for the executor service
Fix for issue 27
added few known transitive verbs .
Add new screencapture . dll for Windows 32 - bit .
Raise toolchain version
drop jdk6 from build matrix , we require java 7
fixed git ignore name
Modified resources . arsc file to make some resources public .
Moved compileSdkVersion and buildToolsVersion on top level build . gradle
Compile tests with source attribute .
Fix up formatting of header after branch
Remove ignored file
more ignore files
Revert wrong version number
Set gradle version to 2 . 2 . 1 for compatibility with Nebula NetflixOSS
FredrichO - fixed spacing on the bottom of the number of columns in the media gallery settings layout .
Create circle . yml
Set isInEditMode ( ) to true # 9
Skip Hive tests under Java 6 , since Java 6 isn ' t supported by recent versions of Hive anymore .
Remove debug statement
prepare release curator - x - zkclient - bridge - 3 . 0 . 0
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
remove mention of GROOVY - 6226 ( Configure Eclipse Plugin ) now that the issue is closed
Introduce internal ` server ` command
Add screenshots from sample application
use the readonly buffer interface when you just need that
Repaired the conflict from wrongly uploaded jar file
Add xml declaration
Fix comment
Remove provided scope of support lib dependency in pom . xml .
updated studio
typo cont ' d ( remove deprecated method in trunk )
Fix build
Change the size of the gifs .
Set the correct version
Include UPGRADING . rst in assembly
Added a gitignore
remove Fixtures . java to test , why was it in main ?
prepare release checkstyle - 6 . 16 . 1
build make buildlog include tests run and fail stacktraces
Temporarily disable MixinC00Handshake
Add more fiels to gitignore
optimized imports
Bump common ref .
Prepare next release v1 . 2 . 1 - SNAPSHOT
Git hygiene
Add maven central repo to readme
rename for letter case
update changelog for 1 . 1 . 1
Don ' t lowercase word vectors by default
update version of build tools
added gitignore .
adding snapshot suffix to version
Set daemon flag on poller threads .
Fix build .
ignored a few more IDEA files
Prepare next release
Set version to be 1 . 0 . 1 SNAPSHOT rather than 1 . 1 .
Exclude pom generated by shade plugin from list of modified files ( minor )
Updated build tools from OC JB workaround app
changed dataset .
Remove the launcher filter from the AndroidManifest as per # 57
Corrected junit jar
keep deprecated requestFBOLayer ( ) method for now .
Ignore gradle related files .
LPS - 63269 apply patch
updating to the latest jain - sip version
Fix # 1173
Upgrade rxnetty version to 0 . 3 . 13
add getCount method to BytesInputStream ( @ MysteryMachine )
Link XPrivacy Installer
prepare release storm - hbase - 0 . 1 . 2
prepare for next development iteration
Remove unused file
added ISchemableSpout interface
Add local . properties to .
Upgrade to Reflections 0 . 9 . 9 - RC2
Remove inspektr dependency version number since it ' s defined in parent POM .
Added reference to distribution .
added shippable builds
added phonegap icon to demo2
Updated the binaries .
updated studio
only write diagnostics log files in desktop mode
fixed test
fixed compilation error
suppress warning
Add service definition so ServiceLoader picks it up
Deploy snapshots of 1 . 1 branch with Travis CI
Release the version 1 . 3 . 0
Implemented getOpacity
set IDEA JDK from build script
Bump common ref .
make Preconditions package private
Testing travis - ci
Bumped minSdkVersion
Add files via upload
Remove nasty mavenLocal ( ) from repositories .
Log stack traces of test failures to the console .
Fix build .
UNKONWN
Updating parent pom version of reporting to 1 . 3 . 0
Preparing for release 0 . 3 . 0
Added files via upload
Added CLA pdf
remove unused resources
updating to the latest jain - sip version
Fix build .
Fix consumerProguardFiles by moving it to defaultConfig
add resource dir for tests
Removed new lines
add 1 . 8 changelogs
Added 2 . 4 . 5 release jar
Add pbethe @ to bazel CONTRIBUTORS .
initial git ignore file
Remove test I opted to host elsewhere
Move GenericKmlBikeRentalSource to correct place .
Ignoring intellij related project files .
Added Data Science doc to H2O - Dev docs site ( 1st new file )
Rogue line number for method declarations confuses IDE debuggers
The / green command should now only affect dirt on the top layer .
Resolve bower dependency conflict , hang ( zeppelin - web )
added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
updated R notebook icon @ kevinushey
Remove NOPASS .
Ignored Eclipse files
Fix profiler after module structure has been changed in pydevd , take 2 ( PY - 18442 )
fixed PY - 6643
prepare for next development iteration
ignored a few more IDEA files
Fix build failure
Remove debug output
Sample gif
Fix build .
Add logging of Bintray user for CI
Added support for automatic legend generation for Wheelchair renderer
fixing GC bug
updated jsr166e to the 9 . 08 . 2015 version
actually run all the tests
Add travis ci
Fix memory leak
Set the correct version
Skip Hive tests under Java 6 , since Java 6 isn ' t supported by recent versions of Hive anymore .
Add self to contributors list ( # 301 )
prepare for next development iteration
Create README . md
Rename LICENSE to LICENSE - 2 . 0 .
Adding top level .
Remove post tag in circle file to attempt build fix
Add ABS as dependency to library ( fix # 559 )
Java regexps do support possessive quantifiers ( IDEA - 81507 )
Change the ignore file .
Updated code .
Prepare change log .
use underlying type for builtins
fix send as picture switcher vertical position in attachment modal
Remove unused import in BufferUtils
bumped elasticsearch api version
Introduce internal ` server ` command
update changelog for 1 . 1 . 1
Fix build .
set org . gradle . daemon = false before running tests in Travis build
Enhanced Windows installer images .
update build tools and target api
Changed field type of username in jiveGroupUser .
Add microbench to the module list
Move file to correct dir
add readme for sample app
added wiki images
missing break in switch
override canNavigateToSource for the future compatibility
Freshen screen shots in help screens
Fix indentation and code style
Bump common ref .
Upgrade rxnetty version to 0 . 3 . 13
added few known transitive verbs .
build make buildlog include tests run and fail stacktraces
added linksource to javadoc so we can navigate from javadoc to source code
Set default attachment preview image in the code ( and not only in layout ) so that whne moving from a message to another we get the right preview
Add changelog to track high level changes of each release
Remove unnessary bundle package
add context accessor for subclasses
Updated springsource logo
Ignore OSX and IDE files
updated min sdk to 11
Upgrade maven version to 1 . 0 . 4
update com . android . tools . build to 0 . 4 .
Added Commander / SourceSafe to the list of checked plugins
Fixed import .
Removing two zero java files
updating to the latest jain - sip version
Create README . md
Updated APK
add base plugin to get clean tasks
Remove unused file
Updated logo more according to new icon
added example images of thumbnails
Add demo gif
keep deprecated requestFBOLayer ( ) method for now .
Add depart icon in itinerary step row
Drop OpenJDK6 from Travis CI suite
Updated gradle from 0 . 6 to 0 . 7
Move atari font notice out of res directory .
specify gradle version
Set source and target compatibility to Java 1 . 7 .
Remove openjdk6 as a platform to build Guava on .
Set minSdkVersion + targetSdkVersion via build . gradle
updated pac4j version to the released 1 . 8 . 2
add eclipse and idea projects to gitignore
Removed un - used p . paused ( ) .
Adding version
update qq
Fix Mock provider after merge of # 51
added travis file
Added a release_description file to be used by CI
Finished top level tool bar and misc fixes .
Updated Ant jar
added changelog for 1 . 6 . 1
revert icon to old one
updated CHANGES
added few known transitive verbs .
resize image
Changed build tools version to 23 . 0 . 3 , don ' t use rc version
Require Maven 3 . 0 .
Allow null string input
Add junit as a dependency for subprojects ( modules )
Add a recent change
Modified resources . arsc file to make some resources public .
Fixed test for changes to ' model ' report output .
Fix checkstyle
uppdate build tools
Modify LICENSE
set IDEA JDK from build script
Bump " demo " to 1 . 1
UNKONWN
remove alert
fixed compilation error
Create img
FastArray doesn ' t overwrite toString ( ) method
Updated doc
updated JettyWebfilterTest . java to JettyWebFilterTest . java
hopefully this will make it render
Add jQuery module
Build fix
Cleaned the directory for .
Fix style on build . gradle
Disable JS tests when enabling the profile dbTests
Returning proper type for config setting .
Prepare next release v1 . 0 . 2 - SNAPSHOT
Delete a . gif
Remove debug printout
Upgraded maven - release - plugin to version 2 . 1 .
Added support for using a transaction to perform batch tasks .
Introduce internal ` server ` command
Include a call to ` ulimit - a ` when building in Travis CI
Removes the TODO to upload the library to bintray / jcenter
update Universal - Image - Loader
Change maven prerequisite to 3 . 0 . 4 to match the maven api version
Fix formatting
Remove test I opted to host elsewhere
updated sign stage
Updated changelog for 5 . 5 . 3 .
Modified url for issue tracking to directly show tickets for the component .
Restored @ since javadoc tag of Convertible
fix for GRAILS - 6503 " WAR does not include JARs from compile - scoped plugins "
Ignore OSX and IDE files
update android native
bump Android JAR version to R4
Add CHANGELOG . md
Fixed version .
Create README . md
remove waiting for device
Added public method to Cache to check initialized state
Fix testdata
Add images for the index file for the SpinnerTest test application sample .
Fix incorrect closing tag
follow / unfollow API
Missing mavenCentral ( ) repository
Move H2OApp into a package
Set the correct version
keep deprecated requestFBOLayer ( ) method for now .
add unistd . h for getpid ( )
Whack version that replaced unexpected - condition error condition with unexpected - request .
UNKONWN
update gitignore with local . properties
add style images
fixed file name of travis script
UNKONWN
added checkstyle file info
Remove unused file
remove debug output
LPS - 66848 Add missing Gitignore
updated version
ignore swp files
Git hygiene
Ignoring build - data .
improved image for the docs
Remove extra newline
trying new build infrastructure
Added gitignore .
Fix checkstyle
Ignore bin and gen
Adding Read icon , updating Dashboard / Reload icons
add travis - ci config
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
upgraded groovy jar again as previous version was corrupted , missing EMC
update to latest gradle plugin
add intention test to all tests suite
Fix # 183 - update screenshots
Updating linux bullet binaries
add missing RCTConvert import
Remove unused var
Resize default xlarge wallpaper .
Cleaned the directory for .
Add missing method
Fix build
add apk demo
Testing Travis Container Environment
Remove unused file
Fix typo
Fix typo
add words
Added screenshots
remove unused property
updated TODO
suppress warning
LPS - 45010 Fix typo
Removed DoubleCheckedLocking from checkstyle . xml .
apply proper quoting to crash arguments
Update doc commit pointer for 0 . 3 . 2 release
Modify changelog
Fix typo .
add jekyll _site directory to .
Started building with java6 because with java7 the javadoc does not look good .
dropped old and unused method
add Sample Apk file
add table of contents in python / README
Updated CHANGES . txt
removing comm files from jre since they needn ' t be in there
Replace screenshot with a new one
Call AudioTrack . flush ( ) before AudioTrack . release ( ) .
Prevent infinite loop on exception
Reordering the build repositories in the hope that this fixes the jenkins build .
fixed compilation error
add getCount method to BytesInputStream ( @ MysteryMachine )
Prevent duplicate loader onLoadFinished calls on config change
Removed unused import
Add eclipse plugin .
update demo app
Added support for automatic legend generation for Wheelchair renderer
Corrected license identifying information .
update com . android . tools . build to 0 . 4 .
add getCount method to BytesInputStream ( @ MysteryMachine )
Number the reference
added war / to gitignore of template
Removed old symbol pattern .
Delete logo . png
Bump common ref .
Bump the version
Revert " Reduced header size "
Add missing curly brace in the README
HHH - 3580 added entity manager to module list
Reinstate view example for screenshot tests
Ignore lint warnings for unregistered activities
Reduce the amount of logging from the Javadoc plugin .
Ignore OSX and IDE files
Updated changelog for 0 . 8 . 3
set the correct version for the branch
Remove empty line
Fix for issue 27
Added support for travis - ci
Fix Makefile to not automatically install node modules
update travis config
UNKONWN
add the snapshot of demo project
rename macro to be clearer that output is to logs
UNKONWN
LRQA - 16067 Add list of product names into test . properties
Adding bin related files to gitignore ( # 130 )
Remove unused constant from TWLayoutManager
GROOVY - 4440 fix Apple ' s L & F detection when running Jdk6 +
Don ' t automatically show the batch buttons when entering multiselect mode
Prepare change log .
bump Android JAR version to R4
Hebrew uses language code iw apparently .
remove unused method
Updated ignore file
die extra plugins
Fix Portuguese docs navbar
Updated version in docs to use 1 . 5 . 0
Remove blank lines
Removed minSdk Call
LPS - 62799 Fix NullPointer in test
updated to ignore merge leftover files ( orig ) and ant builds
bumped version
Ignore Vim / Vi backup & swap files
Enabled Vertical ScrollView instrumentation test in SandCastle
Upgrade maven - javadoc - plugin to its latest version 2 . 9 . 1
remove unused resources
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Add caching of Maven artifacts to Travis CI build
Add art assets
added tablet screenshot
add 1 . 8 changelogs
Fixed the module name
Fix mixed line ending characters in .
Adding image folder for Flow documentation graphics
UNKONWN
Fix build
raise version
UNKONWN
Fixed typo
Remove blank lines
remove a wrong char " 7 "
Removed unused import .
Remove < pre > borders in result frame
Add vcs root
Not using any more
Remove superfluous Ahem . tff
fixed # 1110
Fix cloud status availability from old URL ( v1 ) .
Removed the blue outline from the whiteboard buttons that are selected .
Fixed pom . xml tag
Create Jar artifact with test code
Bump common ref .
add unistd . h for getpid ( )
add Question 4 . 9
Updated build . gradle for maven
Add travis config
add eclipse and idea projects to gitignore
updated release for bug fix
Added Gradle Wrapper Jar
Upgrade version name to 0 . 2 . 3
Fix signing fallback .
disable tests to obtain a cache
Update build branches
Add jar built by Oracle 1 . 6
Added screenshot
Set the correct version
Fixed case of SideBitFlag
Fix build
Fix package in manifest
Removed bottom margin of buttons at the bottom
corrected pt_BR directory name
Add product flavor to reduce build time on debugging
set shell script executable
added travis - ci config
Moved assertThat ( ) back into hamcrest - integration ( really this time ) .
Fix build .
bump jsonassert
bump socket . io
UNKONWN
Fix resources
Ignore gradle related files .
Bump otto
Remove extraneous semicolon .
remove jni . h include from IOMX . h
bump to 1 . 7 . 6 and minor CHANGELOG cleanup
Added new sample APK .
Added Data Science doc to H2O - Dev docs site ( 1st new file )
Fix param for Metrics Consumers
suppress warning
Bumped minSdkVersion
Make 1 . 0 . 0 header the same level as others ( # 2885 )
HHH - 3580 added entity manager to module list
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
Make Tachyon - Perf a subproject of Tachyon
update CHANGES
Moving class to dp package
Added auto unit testing
prepare for next development iteration
Prepare change log .
Remove Notification Center observers on dealloc
Fixed p . filter param
Tell travis to also run the examples
update Universal - Image - Loader
benchmark & update version
deleted tools . jar
Use new sanitizer option .
add in missing module traceback
Add change log .
set IDEA JDK from build script
Update the ptbtokenizer test to reflect the non - americanization
LPS - 56049 Set default project group
Create webapp / llap directory for MiniLlapCluster
Fix build
Log test errors .
Add Travis - CI YAML file - # 722
added kmtoy for ex
Remove unused import
Ignore OSX and IDE files
drop jdk6 from build matrix , we require java 7
jetty - 9 commit test
Ignore temporary generated site .
Get me out the stupid readme file .
disable tool
Add TODO
Adds lintOptions to Library .
MinecraftForge / FML @ e3ce211cc798f4d86ca6f974d9ba8b4e389b4dc9 Nullcheck the dispatchers on players .
Fixed deprecation
Updated build . gradle for maven
The / green command should now only affect dirt on the top layer .
remove repeat lefover . . .
update support jars
Fix stupid copy / paste typo .
UNKONWN
Remove unused import
Updated build . gradle for maven
Fix build
add 1 . 8 changelogs
updated JettyWebfilterTest . java to JettyWebFilterTest . java
Ignore OSX and IDE files
Revert " updated CHANGES "
Make Tachyon - Perf a subproject of Tachyon
removing unnecessary support extra for Travis
Updated support library
Moved logging configuration to the PC Facade where it belongs .
fixed typo in changelog
add function with zero arguments
update slf4j version
Added the legend to the bottom of the graph .
add README
update pom . xml
Fix Travis
Added missing jars from DirBuster integration
Removed some unnecessory code
UNKONWN
Fixed import .
Fix data driven testing example in documentation
UNKONWN
Remove test I opted to host elsewhere
reenable daylight saving test , now that we use joda - time 2
Bump gRPC to version 0 . 9 . 0
Fix for issue 27
assign success variable a value
Ignore OSX and IDE files
meteor / AWSCloudFormation added to validation list
Setting build group and version
remove PIDFILE at stop time
remove web
Write checkstyle to stdout .
build make buildlog include tests run and fail stacktraces
Add callback for ` add ` ( Android )
Fix data driven testing example in documentation
add latest android support lib
Add a .
set version
prepare for next development iteration
Actually fix dupe drop
Fix file name of DeepLinkRegistry and its test
Tweak gitignore .
Fix warning
alternately patched avro jar
Update doc commit pointer for 0 . 3 . 2 release
Added web - icon
Remove old comment
disable bounds checks on release build for samples .
Prepare change log .
removing the pxfetcher module from the gradle settings
Add intellj project files to .
Add isClosed in DruidDataSource
don ' t set the application title in the library
add abortOnError false - so that clean build runs without a problem
update gitignore with local . properties
EftarFileReader . close ( ) cannot throw exception
Remove the over quoting .
update screenshot
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
added a little padding to table cells to improve look and readablity
Add missing method
Updated gitignore to ignore hprof files
Set width of drawer to 320dp
updated 2 . 0 and 3 . 0 plans
Added oraclejdk8 and openjdk8 to the set of CI JDKs
Fixed import .
add new asset for Swagger
regenerate gradle - wrapper . jar with 1 . 9 - rc - 4
Make 1 . 0 . 0 header the same level as others ( # 2885 )
set IDEA JDK from build script
Fix wrong file name
Bumped up parent pom version to solve custom checkstyle issue
reduce T * Map , T * List memory consumption for empty collections ; just like ArrayList did in JDK8
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Start 1 . 4 . 2 version .
Add missing import to chapter six example
Make hadoop directory .
ignore class files in root ( which are generated by " gradle test " )
Fix filename typo
rip off jruby ' s travis notification settings
engines are standalone blocks
Updated copyright date in LICENSE .
suppress warning
Ignore OSX and IDE files
Bumping up version to 1 . 0 . 1
Remove newline in TicTacToe example
prepare release astyanax - 0 . 8 . 10 - SNAPSHOT
Fix build
UNKONWN
remove specify developer team
add blob docs to index
improved handling for Droid Incredible 2
updated pac4j version to the released 1 . 8 . 2
exclude builds for simulator .
update screenshot
Prevent duplicate loader onLoadFinished calls on config change
UNKONWN
add abortOnError false - so that clean build runs without a problem
Fix permissions
update linux amd64 natives
Ignore OSX and IDE files
Updated TeraBullet with fixes to Rigid Body < - > world collisions
Add State and InputStream to the IRecognizer interface
updated gradle wrapper to 1 . 10
Added support for travis - ci
Set isInEditMode ( ) to true # 9
Remove unused file
Ignored eclipse project files .
Remove unused imports
Renaming pom artifact - id , so that gocd shows up instead of main ; when opening up multiple projects in idea .
Remove NOPASS .
Only run compile / unit tests in Travis
Fix build .
Fix warning
Added missing jars from DirBuster integration
add temp directories generated by zeppelin - Rinterpreter to gitignore
comment out snapshot plugin for release
Move hex test to hex directory
remove log4j jar from lib
Ignore bin and gen
Add maven central repo to readme
Add scala back
update changelog , release version to 1 . 5 . 10
Update travis config
LPS - 51912 remove redundant ` continue ` keyword
update logback 1 . 1 . 3 - > 1 . 1 . 5 ( closes # 272 )
Bring the children into the project .
UNKONWN
UNKONWN
Added parsing of Cython typedefs
Commented the missing function viewUpdate ( ) and added a navigator . notification . alert ( " Ready " ) ;
Add images for the index file for the SpinnerTest test application sample .
Bump the version number to 2 . 0 . 6
remove unused jar
Fix build .
Add Small ignore files
disable reloading for scripts with dates in the future
Changed Spout maven repo to more stable url
UNKONWN
Changed field type of username in jiveGroupUser .
Fixed typo in settings . xml
Replaced derpy tabs with spaces
Revert " Change proguard rule to show XPrivacy "
Disable break on lint error .
Updated the .
Move the wcursor increment after the assert
add res directory .
Moved AstBrowserProperties from src / main to src / resources .
Changed components to use parent pom v 4 , producing source and javadoc jar packages .
improved handling for Droid Incredible 2
ignore jar files in beatrix test resources
bumped version code again
Fix bitmap tinting
add getCount method to BytesInputStream ( @ MysteryMachine )
Add local . properties to gitignore
correct null + String to not throw an NPE
Added gitignore .
Appease the checkstyle overlords .
Remove this configuation manipulation b / c it ' s unnecessary .
Prepare next development version .
resize screenshot .
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Change build tools to 22 . 0 . 1 for Travis CI
update xsoup to 0 . 2 . 1 # 75
Adding 2 . 4 . 7 jar
Includes changes to GroovyClassLoader regarding getLoadedClasses method .
Remove temp files
Exclude pom generated by shade plugin from list of modified files ( minor )
Remove mistakenly added module reference .
Disable JS tests when enabling the profile dbTests
add gitkeep for assets
Rename Filter to FilterActivity to prevent name collision
Add microbench to the module list
update changelog for 1 . 1 . 1
Prepare next release v1 . 0 . 2 - SNAPSHOT
explicitly declaring the Locale of JavaDoc task as en_US
Added Travis
Add robolectric cache to gitignore
set version to 4 . 5 for release ( hopefully )
UNKONWN
Fix build .
Add package . html .
Fix build
update build . gradle
Bump parent version to 5
ignore this
add jamm - 0 . 2 . 5 .
Updated version
set IDEA JDK from build script
Use latest syslog4j to unbreak structured syslog parsing in some cases .
cm changes broke this
Fix Groovy - 226 .
FastArray doesn ' t overwrite toString ( ) method
return actual value of isLocal ( ) in command line args
set the version
Add missing method
removed music . ogg from pax
UNKONWN
Prepare change log .
revert version
missed file ?
use the default junit version .
Update SpongeCommon for ' ChangeBlockEvent . Pre ' interact fix .
Add Eclipse specific project files to ignore .
Changed Android compileSdk
Make test NOPASS .
Move H2OApp into a package
Removed unused file .
Add * .
Add a .
Set group and version in top - level build file
Delete banner . png
added info option to travis to output more information
add eclipse and idea projects to gitignore
prepare for next development iteration
add eclipse and idea projects to gitignore
updated 2 . 0 and 3 . 0 plans
Include generated grammars in source zip for debugging purposes
update support version to one in travis ci
Ignore target directories
Skip tests for a while
Build and install the tests jar artifact
Turn off baseline aligment in wide show info layout .
Finish removal of pages submodule
Upgrade jsr305 2 . 0 . 3 to 3 . 0 . 0
Removed Key Value Server from SVN repository .
set the correct version for the branch
added tablet screenshot
Ignore ' travis ' branch to avoid initial build failure .
Write checkstyle to stdout .
remove dependency on react - native which will break the packager
Removed new lines
Move rebalance scripts to bin directory
Fix build
use oracle ' s official jdk
Update doc commit pointer for 0 . 3 . 2 release
set IDEA JDK from build script
add usage
ignore javadoc build error , correct javadoc later .
add context accessor for subclasses
Set minSdkVersion + targetSdkVersion via build . gradle
added gen dir to gitignore
add abortOnError false - so that clean build runs without a problem
Ignore gradle properties file .
Added tag 0 . 5 for changeset 273184406fa1
Make the gradle wrapper executable .
updated icon from Vincent .
LPS - 45010 Fix typo
Exclude gwt files , so that maven tests can run
Parallelize the core tests .
Remove blank line
LPS - 62799 Fix NullPointer in test
Updated CHANGES . txt
updated library
update refs
Fix build
add eclipse and idea projects to gitignore
Bumping version to null
Updated docs
Fix issue with state reset
Upgrade Ivy 2 . 2 . 0 RC to final
ensure utf8 encoding of javadoc
update changelog for 0 . 9 . 0 - rc1 , prep for rc2
Fix build .
Remove blank lines
Fix PyCharm edu icon
add MavenCentrail ( ) in allprojects of build . gradle
Remove outdated ( and wholly unnecessary in this case ) README for wordcount examples
restored nice border effect on footer
bump version for 0 . 9 . 0 release
Fixed import .
Add missing method
Fixed typo
disable tool
remove unused import
bat ` files should always have Windows - style newlines
Prevent duplicate loader onLoadFinished calls on config change
Added changes to changelog
give access to the defining classloader
Add mongodb service for travis config
made publish - maven - artifacts an executable
Remove files from obolete and unused figures
fixed ExpandoMetaClass inheritance and allowed changes to any class used Object . metaClass syntax
Added tag 0 . 0 . 7 . 4 for changeset f415c01ff925
Added oraclejdk8 and openjdk8 to the set of CI JDKs
Add intellj project files to .
Add ulimit printing to travis .
uppdate build tools
Push a AHC Quick Start Guide
Prevent duplicate loader onLoadFinished calls on config change
set the version
Add the isVisible ( ) getter
removed commons lib since now it ' s part of svn repository
Add project files to .
Updated CHANGES . txt
update changelog for 1 . 1 . 1
add new default material images
FastArray doesn ' t overwrite toString ( ) method
Set proper release version
Remove Y
bump to version 1 . 5 . 2
started core project
FIX Dashboard always display a scroll in IE7 ( cherry picked from
help ID ( IDEADEV - 34211 )
update jars
add uaa classpath to eclipse classpath
Add missing override attribute .
Bump the version
remove todo
added gitignore .
add site as a submodule
Bumped up parent pom version to solve custom checkstyle issue
Ignore OSX and IDE files
Set oss parent to 9
learning git
Fix typo
upgrade okhttp 3 . 1 . 2 - > 3 . 2 . 0
Fix xhdpi box
update doc
UNKONWN
fix up test case
Added auto unit testing
comment out snapshot plugin for release
Using new package
fix wrong name
UNKONWN
Added more task to the set of tasks triggered by Travis CI .
ignoring eclipse files
Upgrade rxnetty version to 0 . 3 . 13
change default request connection timeout to 3 secs
added checkstyle file info
rename currents to rapids
Moving to a proper maven source directory
add newline to end of rules file .
LPS - 7366 Remove blank line
Fix a dangling label .
Permit the folder list item to expand vertically .
Removed ci . build = true
Remove unused file
Improved performance for isPresent for windows
Updated API in README
Prepare change log .
add info about " Android - AppMsg - Gradle - Sample " in README . md
Delete lvtea0105
Rename no . properties to nb . properties
remove log4j jar from lib
resized images
added scripts to create heron - tools self extracting binary
missing fields for automcompletion
remove fiel
added Kasper to list of developers
added link to issue
set the version
Ignore IntelliJ ' s .
Fixed import .
Write checkstyle to stdout .
Fix travis error
Renaming pom artifact - id , so that gocd shows up instead of main ; when opening up multiple projects in idea .
deleted tools . jar
Move META - INF / plugin .
update changelog for 1 . 1 . 1
set the version
remove unused source file
added index graph for wiki documentation .
remove unused method
add abortOnError false - so that clean build runs without a problem
removed dependency - reduced - pom . xml from .
Restored @ since javadoc tag of Convertible
remove use of deprecated property on Test
revert committed configuration
Add travis file to continous integration
Updated the .
Added gitignore .
improved image for the docs
Disable mocking " promise " in OSS Jest tests
Add handler for download event
change the permission of make . m to 644
Remove redundant entries .
Added files via upload
add context accessor for subclasses
Prepare next release v1 . 0 . 2 - SNAPSHOT
add eclipse and idea projects to gitignore
added travis - ci config
Create a Plugins . sbt file for required build plugins - currently just the sbt - pgp plugin .
changed publishJavadoc task from Copy to Sync
Git hygiene
debug mode screenshot and miniature
avoid nexus username and password on normal build
fixed description
add gitignore
bump to version 1 . 5 . 2
update windows natives
Remove log4j . properties from test - jar .
ignore IntelliJ files
add style images
prepare release checkstyle - 6 . 11 . 2
Add missing method
Set isInEditMode ( ) to true # 9
remove mention of GROOVY - 6226 ( Configure Eclipse Plugin ) now that the issue is closed
Making default Socket timeout 20s ( from 8s ) .
Added toString ( ) method in NeoApp . NeoAppRelationshipType . . . otherwise
Write checkstyle to stdout .
starting 0 . 5 . 3 - SNAPSHOT
Updated code .
Added run target .
Revert parts of the .
Remove extra newline
updated sonatype parent pom version from 7 to 9
Prepare release 3 . 1 . 0
Log test errors .
updated version
Delete truth jar which I forgot to delete when removing Ant support .
Add Application class .
don ' t need this guy
Update doc commit pointer for 0 . 3 . 2 release
Added files via upload
UNKONWN
Remove unnecessary code
Fixing GLIBC 2 . 4 problem on Debian system .
Removed some unnecessory code
Print current running unit test in pulsar - broker ( # 57 )
Fix style on build . gradle
Bump the version
Upgrade version library to 1 . 1 . 0
increased the default permgen
Index Update Settings API does not update settings in real time , closes # 1807 .
UNKONWN
Added tag 1 . 0 - RC1 for changeset 4daa5ed3ef0e
build make buildlog include tests run and fail stacktraces
Prepare change log .
ignore screenshots from tests
Update build branches
Delete build . gradle
update assertj to test scope
update CHANGES
edit screenshots
update CLA so it can be used for any project
Fix build
Remove unused import
suppress warning
UNKONWN
remove empty file
updated version
Add getOnFocusChangeListener to View
Excluded testNg until Gradle migration is ready .
Remove duplicate of me in AUTHORS
Start 1 . 4 . 2 version .
Add missing villager sounds .
Configured surefire to use UTF - 8 so that Aslak can write & read his
prepare for next development iteration
Removed unused images
Gradle required 2048 heap for multidex
Bigger moving average range in importer
Updated changelog and contributors file
added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
MinecraftForge / FML @ e14efe786f6255a18e148c4137f560f5e2d2a38f Some fixes and tweaks
ignore swp files
Ignore OSX and IDE files
ignore intelliJ files
Reduce the amount of logging from the Javadoc plugin .
Updated build . gradle to point to the strangelydim maven repo again for the latest Agrona snapshot jar .
remove obsolete drawable
update javadoc
Set the correct version
remove unnecessary config properties
Added 5 new biomes as included in MC 1 . 1 as part of # BUKKIT - 496
Drop cached qualified name after changing nodes in subtree
Exclude files generated by ADT from git
Add maven central repo to readme
removing empty lines
Updated code .
Fix floating point exception in emulator
Adding * .
Removed old symbol pattern .
update druid
Override script to skip connectedCheck for now
Missed import
UNKONWN
add deskshare folder
update dict
Putting tests in correct location
Add ignores for idea and eclipse project settings
update joda - time to 2 . 8
Correct a typo .
udpated the read me
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Remove unnecessary code
Fixed proguard issues
updated screenshots
update wiki
make dummy change and assert CC is updating correctly
Reduce the amount of logging from the Javadoc plugin .
LRQA - 16067 Add list of product names into test . properties
Update the ptbtokenizer test to reflect the non - americanization
do not show gpx export items at start
Release pegasus 2 . 6 . 3 .
Fixed color
Build fix
Fixed static use for tic 323
Resize default xlarge wallpaper .
Fix enforcer rule for java 7
Invalidate ActionMode content rect on scroll .
Fix the issue where the loader ( spinning wheel ) locks out the entire page when it is loading .
add jamm - 0 . 2 . 5 .
Added files via upload
Remove unused file
Increased RCTInlineValueThreshold for asynclocalstorage
Fix data driven testing example in documentation
Removed large unused images
remove useless annotation
improved handling for Droid Incredible 2
delete old jar
Adding more temp files to gitignore
adjusting changes . txt
forgotten jars
Ignore OSX and IDE files
LPS - 63269 apply patch
Include lib / instead of libs /
Removed DS_Store files
Fix ABS repo for 1 . 3 release ( close # 134 )
Added toString ( ) method in NeoApp . NeoAppRelationshipType . . . otherwise
added checkstyle file info
Prevent duplicate loader onLoadFinished calls on config change
add eclipse and idea projects to gitignore
Fixed static use for tic 323
add changelog for June 2015
Fix for issue 27
Bumped version to 5 . 0 . 0 - alpha4
fix build for example project
Ignore IntelliJ IDEA files
added intellij specific file to .
Fix changelog
Update build branches
add eclipse and idea projects to gitignore
Removing return statement so that the adapter always reloads the posts list after a post fetch .
removing empty lines
Added checkstyle to core and cache module
Add specific xcode sdk to travis . yml
remove marker
Delete a local ref in getSurface
Include a call to ` ulimit - a ` when building in Travis CI
increased version to 1 . 0
Added missing JNA jar
Remove unused file
update to latest android iconics - core
Updated doc
fixed broken test case
Removing swp file
Remove circleci config
added package . html
Resized header
Added volley . jar to the project
moved TestNGListener from src / main to src / test
Set jdiff version
Set minSdkVersion + targetSdkVersion via build . gradle
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
updated version number
Releasing v8 . 0 . 5
adding build and lib folder while ignoring their contents .
build make buildlog include tests run and fail stacktraces
Ignore OSX and IDE files
Updated the zip file .
added gitignore to blob
update changelog for 0 . 9 . 0 - rc1 , prep for rc2
ignore * ~ from hg
Remove comment
Set isInEditMode ( ) to true # 9
Updated Ant jar
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
comment out snapshot plugin for release
Added translation using Weblate ( Turkish )
Add pointer to h2o - 3 repo .
Remove setting applicationId from library configuration
Added files via upload
update capture gif
fixed typo
Updated help jar prior to weekly release
build make buildlog include tests run and fail stacktraces
Update doc commit pointer for 0 . 3 . 2 release
UNKONWN
updated credits
Fix travis compilation
do not show gpx export items at start
Remove NOPASS .
update factory images
Remove unused file
Bump the version number to 2 . 0 . 6
updated distribution . xml to include whirr recipes and configuration files .
LRQA - 16067 Add list of product names into test . properties
Ignore patterns
do not show gpx export items at start
Give a useful error message when the neo4j shell script gets no command
update the project
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
bump to version 1 . 5 . 2
preserve generics parameters when create methods for parameters with default values
Add missing method
Add a repository block to library only section . . .
fix some bug . . . . . . 123
Fix the build
Make 1 . 0 . 0 header the same level as others ( # 2885 )
Added HdrHistohram . jar to base directory for convenient downloading
fixing warning
Remove assets which are no longer used .
Reverts removal of @ JsonIgnore on Event . type field
Rename MENU . md
Make Tachyon - Perf a subproject of Tachyon
update gradle
LPS - 44121 Add support for internal type in SDK
Testing Circle CI
add maven . test . failure . ignore to true
set IDEA JDK from build script
CHanged target build sdk for osmand
Fix typo in build file
Fixed import .
upgraded guava to 20
Make Tachyon - Perf a subproject of Tachyon
UNKONWN
Adding sample pages to web - service
added package . html
Remove unnecessary code
add function with zero arguments
update maven - release - plugin to 2 . 5 ( fixes issue where release fails to tag properly )
gh - 425 - added empty context xml file to rest api
Delete obsolete icon
Fixed CCE ( EA - 38206 ) .
fix wrong name
Add travis status badge to README .
Added a gitignore
Set version of gpg plugin .
gradle should output the stacktrace for test failures
Fixing null values in first domain trust array entry
LPS - 56049 Set default project group
ignore mac finder droppings
Only show warnings and errors from maven - javadoc - plugin
MinecraftForge / FML @ d00feb58c762b0bbc506d79faf1ce40bc96732e9 Remove debug code that was causing console spam in Forge .
remove extra line
Add a META - INF / services file specifying JimfsFileSystemProvider as a service provider .
Require Maven 3 . 0 .
Get me out the stupid readme file .
optimized imports
Set proper release version
Fix mCoveredFadeColor setter
Fix build .
add function with zero arguments
build trove4j to be compatible with 1 . 5
using gradle
UNKONWN
updated min sdk to 11
added info option to travis to output more information
add a blank line to try and test github webhook
Removed unused import
Remove hardcoded test path
Delete the localrepo .
LPS - 64187 update package info
Finish removal of pages submodule
Ignore IntelliJ IDEA files
Fix build script for generating md5s
Fix build .
update changelog for 1 . 1 . 1
Add Eclipse ' s bin / folder to .
Set bg and fg colour in site . css
update build tools and target api
update to latest android iconics - core
Remove vim command
Use Java 7 on AppVeyor
Moving changelog wikipage to AsciiDoc
add eclipse and idea projects to gitignore
Expanded the ZAP help sections corresponding to Authentication and Users
remove PIDFILE at stop time
removed poms
Delete truth jar which I forgot to delete when removing Ant support .
Delete default README
updated pac4j version to the released 1 . 8 . 2
Updated build . gradle for maven
STORM - 751 Move javadoc aggregate to site phase .
add intelliJ files to gitignore
Introduce internal ` server ` command
Need a CHANGELOG . md for bintray automation
Release pegasus 2 . 6 . 3 .
ignore * .
update windows natives
Remove extra newline
Fix un - updated rule change
Use newer sonatype pom .
Fix OF - 654 - Limit index size of JID to 256 for mysql
Add unzip as a dependency
Bumped JadConfig to version 0 . 3 , fixes SERVER - 59
updated sonatype parent pom version from 7 to 9
update windows natives
add getCount method to BytesInputStream ( @ MysteryMachine )
add missing task dependency to kotlin example
trim some fat
Use new sanitizer option .
Updates
Add margin clear button
added brew upgrade to MacOSX build instructions to avoid boost error .
resize image
Updated dslv submodule
Add solid shadow .
add html attribute
Fix build .
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Added missing JNA jar
ignore properties )
MinecraftForge / FML @ c48b48ee15f38d3e794b6eb3499c536226ca5a79 Fix server launching .
Fixed static use for tic 323
updated sonatype parent pom version from 7 to 9
fixed the build
Updated project . proerties to build with latest SDK .
Add flowdock notification to Travis build .
Prepare repository for the next development iteration
Remove local testing file
Releasing v8 . 0 . 5
fix compile error
Updated Ant jar
Add config for Travis CI
Fixing transitive - ness of provided
Fixed overflow rounded icon in xxhdpi
Added files via upload
fix bug
Make notest .
changed license name
Begin development of 1 . 11 .
missing icon
Delete build . gradle
remove newline
Fix crash on Windows x64 when receiving video , add native Windows video renderer for 32 - bit and 64 - bit .
Bumped version
upgrade XStream 1 . 3 - > 1 . 3 . 1
don ' t set the application title in the library
Set the correct version
Added files via upload
ignore all classpath / target / .
Remove extra newline
Bump readme version
Added translation using Weblate ( Polish )
Rename COPYING file to LICENSE
remove warning
remove blank line
Added John Wagenleitner to the contributors
UNKONWN
updated credits
Remove unused file
Fix release number
Update uploads view when finish upload is deleted
Fix build
ignore IntelliJ files
Eradicate whitelisting
disabled failing test
Add platform - tools to .
trim some fat
updating to the latest jain - sip version
Updated version
- Incorrect link in " Break tab " help pages
so release local reference
add JSR 305 annotations jar
Added 16x16 icon
Updated support libs to 23 . 3 . 0 .
Fix check for ANDROID_HOME environmental variable
add rm
Stop Gradle from destroying IntelliJ project settings
update build . gradle
Add fatter divider on xhdpi devices .
Return the record state locked
Added React import to android VideoPlayer Example
Removed unnecessary asset
Updating README .
update javadoc
Copy the resolver configuration when cloning Bootstrap
fixed typo
add iframe option
Avoid infinite loop
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Fixed import .
Added VIM temp files to gitignore .
using bash specific syntax , so should declare rith shebang . . .
Updated gitignore to ignore hprof files
add seaborn to requirements . txt
Added support for automatic legend generation for Wheelchair renderer
Remove test I opted to host elsewhere
Remove AppState from Known Issues page
Moves stray java test class from top level project into pig module
Fix css
prepare for next development iteration
LPS - 58931 Move the media wiki zip from portal to its bundle
fix some bug . . . . . . 123
Prepare change log .
Not using any more
Fix a test using model report after making binary tasks visible in the model space .
Fix typo .
Add shared element screenshots
Remove unused file
Bump pegasus to 1 . 9 . 5
add blob docs to index
Remove obsolete file
Added a id to thumbnail + maincontent layout
Change game category image .
Setting default name for multi - project
Remove unused import
Added Travis
Moved logging configuration to the PC Facade where it belongs .
Shrink notification area to contents
Added 5 new biomes as included in MC 1 . 1 as part of # BUKKIT - 496
update concurrentlinkedhashmap - lru to 1 . 4 version
added few known transitive verbs .
UNKONWN
Prepare next release
Updated version
Put maven central back
Set oss parent to 9
use the readonly buffer interface when you just need that
Setting build group and version
Fixed typo in the changelog .
Ignore OSX and IDE files
help ID ( IDEADEV - 34211 )
Add pointer to h2o - 3 repo .
debug mode screenshot and miniature
updated images for checkboxes and pagertabstrip
textIsSelectable = " true " to comment detail
Use the correct language code for Korean
Fix mistype
Add files via upload
Ignore OSX and IDE files
set the correct version for the branch
Require Maven 3 . 1 . 1 or above
Fix an example of Tree model JSON output
Fix travis config , again
reenable daylight saving test , now that we use joda - time 2
added a test case for GremlinEngine . . . Going to probably rename these to GremlinScriptEngine and GremlinScriptEngineFactory to be consistent with other ScriptEngine classes .
Corrected typo in help
Fixed incorrect value for ChatColor . BLACK ( was 1 , should be 0 )
Add help .
improved handling for Droid Incredible 2
Add service graphs
updated font file
Removed unnecessary @ SuppressWarnings
remove uneccessary whitespace .
Move groovy . icns to lib
add release notes
Upgrade ASM to 5 . 0 . 2
remove bin directory
UNKONWN
Fix for issue 27
Start 1 . 4 . 2 version .
fix the misleading model_key name
Update SpongeCommon for DestructEntityEvent cause improvements .
Add checkstyle plugin to lifecycle mapping exception to get things work without warnings on Kepler .
update windows natives
deleted unused changelog
removed unnecessary import
Bump gherkin
Fix build
remove log4j jar from lib
Add file local variables to build . xml
update contributor list , add yaphet , bjlindeqiang , dingjun , Dollyn , feilaoda
do not show gpx export items at start
ignore " bin " directory ( created by Eclipse )
update linux - arm native
Fix DRF / GBM tests - Gaussian deviance now works .
update jacoco to 0 . 7 . 0 ( IDEA - 123499 )
Upgrade maven - javadoc - plugin to its latest version 2 . 9 . 1
made logo smaller
No longer skip integration tests on Jenkins
Add Travis Build
Fix build .
Added John Wagenleitner to the contributors
remove blank line
Adding hero image .
fixed version
removed dev import .
Make 1 . 0 . 0 header the same level as others ( # 2885 )
Delete help button from postfix completion configurable
fixed ExpandoMetaClass inheritance and allowed changes to any class used Object . metaClass syntax
Added toString ( ) method in NeoApp . NeoAppRelationshipType . . . otherwise
disable tool
Delete lvtea0105
Use netty - 4 . 0 . 17 .
Removed @ Ignore from a passing test .
Index Update Settings API does not update settings in real time , closes # 1807 .
Ignore target directory
add Archive keyboard shortcut to MessageList , refs issue 3
Upgrade ZkClient to 0 . 8
Build ' client ' target with - Wno - sign - compare .
remove swp file
Fix bug in travis
remove final
Build tools version updated to 22 . 0 . 1
Add notification icon for use with Android 1 . 5
Prepare change log .
updating astyanax version to 2 . 0 from 2 . 0 - beta
Fix Travis
bump to 1 . 7 . 6 and minor CHANGELOG cleanup
Fixed static use for tic 323
added new configChang handling for certdisplay
Modified resources . arsc file to make some resources public .
Increase the delay a little bit when opening a new activity from the MenuDrawer .
Fix style on build . gradle
Bug 4588114 - Make GestureDetector behave nicer with parallel multi - touch detection
Missing Icon files .
Marking 9 . 3 . 8 as clirr comparison
Fix build
Update SpongeCommon for PlayerChangeClientSettingsEvent posting fix
Make the gradle wrapper executable .
Introduce internal ` server ` command
Ignore OSX and IDE files
Ignore OSX and IDE files
commented out a failing line
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Added tag 0 . 0 . 7 . 8 for changeset 9bb7ad84eace
prepare for next development iteration
add eclipse and idea projects to gitignore
Added a gitignore
Properly handle empty layout in getFirstVisiblePosition ( )
Removed android - support - v4 . jar .
Add Eclipse files to .
Add Maven artifacts to .
Add images for the index file for the SpinnerTest test application sample .
kindle branch
Removed Merriweather light variation assets ( since they won ' t be used )
Revert " Make sure .
remove fiel
Move test data file to correct location .
add a - d flag to dpkg
Ignore a png file that ' s a documentation build artifact .
Added AppCompat & RecyclerView libraries
Added bin / to ignored files for Eclipse users
Don ' t show strange exceptions on shutdown ( PY - 5417 ) .
Upgrade Apache Commons Collections to v3 . 2 . 2
remove unused method
keep deprecated requestFBOLayer ( ) method for now .
Fix warning
update CHANGES
Removed new lines
Remove duplicate of me in AUTHORS
Fix typo
Fix data driven testing example in documentation
Adding a previously forgotten resource to git
prepare for next development iteration
Set the correct version
Bump Spongecommon for EnderDragon Respawning fixes .
update refs
Add gitignore
removed querydsl - scala / .
update Universal - Image - Loader
Fix build
UNKONWN
Remove unnecessary dependency
LPS - 52060 update sdk
Added example .
No longer skip integration tests on Jenkins
Rename COPYING file to LICENSE
Fix changelog
Added symbols . macosx .
remove unused WORKER - HOOK - FIELD def
update changelog for 1 . 1 . 1
Revert default behavior of " Back Key " to exiting application .
Remove unknown app module
Fix test failures for CASSANDRA - 5175
LPS - 44121 Add support for internal type in SDK
remove unused method
LPS - 27200 Jetty needs JNDI
Bumped JadConfig to version 0 . 3 , fixes SERVER - 59
ignore content generated by grunt
Fix typo .
Ignore reports directory .
Remove a spurious symlink
Bump readme version
missing icon
Add some gitignores
reset version for development
Exclude pom generated by shade plugin from list of modified files ( minor )
build make buildlog include tests run and fail stacktraces
fixed compilation error
Set travis jdk to java8
build make buildlog include tests run and fail stacktraces
renaming the test to correspond with the interface rename
Add break line
Fix bug 3425610 Adjust Lock sound level
add iframe option
Remove NOPASS .
Update build number and version name for 2 . 6 beta 1 .
Remove empty line
update changelog for 0 . 9 . 0 - rc1 , prep for rc2
Add missing README link to Sonatype snapshot repo .
remove libsvm . jar
Updated Support Libs to 23 . 4 . 0
do not show gpx export items at start
Moving changelog wikipage to AsciiDoc
Adding sample pages to web - service
Generate XML reports from JUnit test reports
build make buildlog include tests run and fail stacktraces
update xsoup to 0 . 2 . 1 # 75
Add gitignore
Relocates maven push script to repository root to allow for use by other modules .
Publish gradle - logging artifacts
bump up 1 . 1 . 0
Add missing import to chapter six example
add words
UNKONWN
UNKONWN
Fix typo .
Ignore all .
Make sure .
Added toString ( ) method in NeoApp . NeoAppRelationshipType . . . otherwise
Don ' t run emulator and exclude github pages for builds
Add service graphs
Fix build .
Removing legacy dependencies
Copy the XML descriptors .
update thrift jar to current recommended revision
Downgrade Hamcrest matchers .
add Travis CI configurations .
Build and install the tests jar artifact
Add product flavor to reduce build time on debugging
build make buildlog include tests run and fail stacktraces
Fix build
added screenshots
updated version number
Moving STUN sources from Openfire codebase to plugin .
Remove unused constant from TWLayoutManager
Suppress warning
Remove blank lines
Adding Client Load - Balancing diagrams
mention 5950 in NEWS
updated version
Disable break on lint error .
update changelog , release version to 1 . 5 . 10
Added art folder
LRQA - 16067 Add list of product names into test . properties
Add missing line
Added files via upload
Create img
Fix solaris build
add gitignore
Ignore OSX and IDE files
update demo
Set the correct version
add function with zero arguments
UNKONWN
Add missing < limits . h > include
changed a typo from SHNAPSHOT to SNAPSHOT = )
Added grails central plugin repo back in as a dependency repository .
Disable cobertura travis portion ( # 3122 )
build make buildlog include tests run and fail stacktraces
Removed @ Override flag from compareTo method , since it isn ' t in the superclass .
UNKONWN
Make 1 . 0 . 0 header the same level as others ( # 2885 )
update Alipay and Weixin
Add circle . yml
Upgrade rxnetty version to 0 . 3 . 13
Update travis config
Bump the version
add readme for sample app
Added StatefulPersistenceContext . getProxiesByKey ( ) ( needed for testing non - flushed changes )
updated jar
Build the JNI lib as a dependency rather than packaged
Added Travis
fixed memory leak
added circle . yml
prepare for next development iteration
Add toString ( ) to IndexShardGateway
Prepare next version ( 0 . 3 )
Find - > Search
Fixed bug of disappeared rounded angles after first display
rename dir
fixing syncDoc task to avoid up - to - date message only because target directory already exists
build trove4j to be compatible with 1 . 5
Added JUNGLE tree to TreeType enum - this fixes BUKKIT - 886
Use the Cache for ~ / .
removing extra lines
added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
improved handling for Droid Incredible 2
updated version
Add State and InputStream to the IRecognizer interface
updated todo
removed System . exit ( 0 ) from RunTests
remove empty file
remove old cmd option from usage sysnopsis
delete README
Set minSdkVersion + targetSdkVersion via build . gradle
keep deprecated requestFBOLayer ( ) method for now .
Moved logging configuration to the PC Facade where it belongs .
add style images
Fix fbthrift script
Upgrade gradle
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
Fixed static use for tic 323
Download apk directly from here
Create README . md
Add local . properties to gitignore
move sql reference and rest documentation at end of ( sub - ) TOC
Putting tests in correct location
Bumped docs version to 2 . 5 . 0
missing colon
Change the flowdock notification for Travis builds .
Set animation to null after canceling current anim .
Updated CHANGES . txt
Prepare library for release 2 . 1 . 4
adding shim . R to description
Ignore bin and gen
Ignore OSX and IDE files
temporarily disable test
Add project_config to sdk module
removing dangling directory
Set proper release version
Updated library name
Prepare next version ( 0 . 3 )
Add vim swp files to gitignore .
update weex - transformer to matched version
Log test errors .
