update changelog for 1 . 1 . 1
missing icon
TFJ - 266 fixed test . properties
Added missing JNA jar
Updated JavaApplicationStub , which runs both on Leopard and Tiger .
Fix build .
prepare for next development iteration
Resolve bower dependency conflict , hang ( zeppelin - web )
Ignore project icons
Added files via upload
Add Eclipse 4 . 5 new workspace folder to .
removed unnecessary import
Added the reduce function to the manual
Set the correct version
Remove circleci config
removing dangling directory
Restored @ since javadoc tag of Convertible
add a blank line to try and test github webhook
Added tmp / to .
Eradicate whitelisting
Updated changelog for 5 . 5 . 3 .
Removed DS_Store files
Fix typo .
add the mavencentral repository on the root level
added few known transitive verbs .
updated documentation in alpha rather than random order
Updated notification icon for Android 2 .
Change xml tags order .
remove specify developer team
Disable clip to padding for row items to avoid clipped transition animation
update changelog for 0 . 9 . 0 - rc1 , prep for rc2
Begin development of 1 . 11 .
updated file
remove mail notifications ( for now ) from travis
remove debug line
remove PIDFILE at stop time
Add building buck completed line
build config fix
Set the correct version
Fix build issues
add overlay
When closing the stream for the host ' s web . xml if an exception occur then hostTimeStamp must be set to - 1 and not the globalTimeStamp .
Updating parent pom version of reporting to 1 . 3 . 0
Add screenshots
add ignore for jre . tgz on linux
Fixing GLIBC 2 . 4 problem on Debian system .
Fix log version string .
update changelog for 0 . 9 . 0 - rc1 , prep for rc2
Suppress warning
Fixed method layout in ActivityApp
Turn off baseline aligment in wide show info layout .
added newline .
Updated version
Prepare change log .
fix travis config
added few known transitive verbs .
Build fix
Skip deployment of integration - tests
Require Maven 3 . 0 .
Remove mavenLocal ( ) from buildSrc
update changelog for 1 . 1 . 1
remove old
added few known transitive verbs .
add eclipse and idea projects to gitignore
Added docs for the docs .
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
added Travis CI configuration .
Add shell script for zan
Fix for issue 27
disable tests to obtain a cache
Eradicate whitelisting
update changelog for 1 . 1 . 1
corrects tests for GROOVY - 2774
remove todo
started core project
Update doc commit pointer for 0 . 3 . 2 release
help ID ( IDEADEV - 34211 )
Updated CHANGES . txt
make build . sh executable
starting 0 . 5 . 4 - SNAPSHOT
LPS - 22149 - This will lockup the browser
bump to version 1 . 2 . 1
Doubles the height of chunks ( once again ) .
Add glyphs for Vertical Text
Remove unused file
updated CHANGES
Add Eclipse files to .
rename unit - tests execution to default - test
Added a release_description file to be used by CI
Modify changelog
force 3 jvms even if multi - machine
add table of contents in python / README
Should fix black laser beams .
Added gitignore .
added checkstyle file info
set the version
Remove debug statement
Removing unused imports .
Fix build .
update changelog for 1 . 1 . 1
update changelog for 1 . 1 . 1
Prepare change log .
Add commons - collections jar .
activated " testIteratingWithList " test
suppress warning
regenerate gradle - wrapper . jar using 1 . 10
typo , removed sys accidently a couple days back
regenerate gradle - wrapper . jar with 1 . 9 - rc - 4
more on greenify some plugin . xmls
Included string . h to use memset in stress . cpp
removed the lcrypto BouncyCastle lightweight crypto library , since the source is now part of the project directly as info . guardianproject . bouncycastle
add bin to gitignore
updated sonatype parent pom version from 7 to 9
Add icon # 1416
update refs
Set version to be 1 . 0 . 1 SNAPSHOT rather than 1 . 1 .
Removed old symbol pattern .
correct null + String to not throw an NPE
Added app icon for xhdpi
Updated travis config
bump to version 1 . 5 . 2
can ' t access static field from nested closures
Add toString ( ) to IndexShardGateway
Fix typo which cause stack overflow if children ( ) was called
Remove a spurious symlink
Create grade files to appease NetBeans plugin
Add support lib to Sample project
follow / unfollow API
set IDEA JDK from build script
add iframe option
Ignore OSX and IDE files
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Build the JNI lib as a dependency rather than packaged
reduce T * Map , T * List memory consumption for empty collections ; just like ArrayList did in JDK8
Updated build . gradle for maven
Fix build errors with m2e
Make notest .
added coverage to test interfaces
Add commons - collections jar .
Use new sanitizer option .
Suppress warning
updated studio
Make privacy provider single user for multi - user environments
Prepare next release v1 . 0 . 2 - SNAPSHOT
Add org . jetbrains . android as dependency
Add gitignore file , clean Broadcaster internals when invoking destroy
Fixed import .
Add * .
added favicon
Remove the background from the RelativeLayout , allowing the ActionBar style background to show through
Added support for using a transaction to perform batch tasks .
Created PopularMoviesView
add missing import
Ignore project configuration files for NetBeans
updated credits
added changelog for 1 . 6 . 1
Upgraded Wrapper
Should fix black laser beams .
run tests in build
Permit the folder list item to expand vertically .
Updated notification icon for Android 2 .
Add project_config to sdk module
Remove unused file
bump to version 1 . 5 . 2
Upgraded maven - release - plugin to version 2 . 1 .
Replace menu title image
Updated build . gradle to buildToolsVersion " 21 . 1 . 1 "
add unique to python
add readme
update changelog for 1 . 1 . 1
update osx natives
update changelog for 1 . 1 . 1
Added the legend to the bottom of the graph .
Move the Swing Model test to swing module as well
Ninja fix CommitLogStressTest . testRandomSize
Added checkstyle to core and cache module
Remove unused import
ignore maven target folder and eclipse project files ( .
added index graph for wiki documentation .
build config fix
removing empty files
Update the alias in the server side trust store to match the name used for the certificate .
Removes extra padding introduced during merge from develop
use the latest networking version
Upgraded wrapper
update changelog for 1 . 1 . 1
Zeppelin Server doesn ' t catch all exceptions when launching interpreter . sh
Temporarily disable MixinC00Handshake
Bump pegasus to 1 . 9 . 5
build make buildlog include tests run and fail stacktraces
Create README . md
die extra plugins
Remove Y
ignore class files in root ( which are generated by " gradle test " )
Adding a ' .
Fix build
Fix build .
Skip javadoc
Add steam output to .
Add more eclipse project configuration
Add javadoc plugin
update changelog for 1 . 1 . 1
Add final newline to editorconfig .
remove debug line
Fix OF - 654 - Limit index size of JID to 256 for mysql
prepare for next development iteration
Renamed test process to make the test run on case sensitive operating systems
Fixed import .
Fix build
Bumped up parent pom version to solve custom checkstyle issue
remove unused method
adding jna for native library access
remove swp file
Permit the folder list item to expand vertically .
Added person .
Removed some unnecessory code
Remove NOPASS .
upload demo gifs
add icon
add change
Have a bottom actionbar in the Search activity to be consistent .
Fix a rare NPE crash in Android 2 .
Added StatefulPersistenceContext . getProxiesByKey ( ) ( needed for testing non - flushed changes )
updated documentation in alpha rather than random order
Move the wcursor increment after the assert
Make text in table wrappable
update refs
Add vcs root
Fix permissions
Remove temporary test
do not show gpx export items at start
improved handling for Droid Incredible 2
add " cpp " target to build OTF decoder and OTF decoder doc
Removed unused resurce
remove unused logger
Added screenshot
update thrift jar to current recommended revision
update idea 128x128 win icons
Add caching of Maven artifacts to Travis CI build
Tweak gitignore .
Updated build . gradle for maven
Log test errors .
Remove unused file
Fix typo
remove warning
added idea ignore config
do not show gpx export items at start
Fix IndexOutOfBoundsException setSpan happening on Samsung devices by simply disabling long click events on edittext .
Adding binary dependencies for aapt
Fix build .
Fix build
Change Sorbian ISO 639 - 2 from wen to hsb
Don ' t delete jars
add deprecated application . properties to skeleton
Ignore gradle related files .
update refs
LPS - 48133 update SDK
add antlr - 3 . 1 . 3 ( should have been in r761805
Add missing LOCAL_MIN_SDK_VERSION for Support Library demos
Pushed CUnit back to 1 . 12
Remove the superfluous ProGuard rule for the database package
Prepare change log .
Add more eclipse project configuration
Update SpongeCommon for DestructEntityEvent cause improvements .
LPS - 63269 apply patch
update osx / darwin native
Upgrade rxnetty version to 0 . 3 . 13
Removed javadoc dependency from javadocJar method to avoid automatic javadoc build
bump socket . io
Fix a MethodSelectionException for Java 8 ( # 421 )
Add getOnFocusChangeListener to View
Prepare change log .
just added author tag
Added public method to Cache to check initialized state
updated pom . xml to use graphdb - deps - all - 0 . 3 .
Set VERSION to 5 . 3 . 0 - dev ( via coho )
add eclipse and idea projects to gitignore
Updated Ant jar
Add forgotten static file robots . txt
bump to 1 . 7 . 6 and minor CHANGELOG cleanup
Fix build .
Remove unused var
update travis . yml
change wl12xx hotspot ssid to spike
add maven support
included default .
CHanged target build sdk for osmand
fix wrong name
Remove unnecessary code
added ForbidAnnotationElementValueCheck
updated apk
use the latest 0 . 10 . 103 version
bumped min maven version to 3 . 2 . 1
Remove unused import
Remove unnecessary code
updated CHANGES
rename file so its title has a space in it
Fix build .
removed package statement as we ' ve stuff in groovy .
comment out snapshot plugin for release
disable tests to obtain a cache
remove deprecated @ S3method roxygen2 completion
make start . sh executable
Add * .
bump version for 0 . 9 . 0 release
Add CodeNarc rule exclusion
do not show gpx export items at start
Added Makefile for R .
updated fake - dom with functions for ComputedStyle
add getCount method to BytesInputStream ( @ MysteryMachine )
Fix build .
bumped version
add toString ( ) to GoLightType
set IDEA JDK from build script
Set source and target compatibility to Java 1 . 7 .
Fixed validate IPv4 address method
Fix broken image
Make 1 . 0 . 0 header the same level as others ( # 2885 )
Added missing script line
Add gradlew . bat to .
Added failing test for JSON output
updated min sdk to 11
Added docs for IDE / plug - in
Updated CHANGES . txt
Remove unnecessary code
update changelog for 0 . 9 . 0 - rc1 , prep for rc2
Bump common ref .
Call super . onDestroy ( )
Remove extra newline
Add a note about changes .
Delete default README
prepare release HikariCP - 1 . 3 . 7
Updated structdb
updated version
add res directory .
adding gitignore file
Fixed version .
Add Eclipse files to .
Added person .
comment out snapshot plugin for release
Should fix black laser beams .
trim some fat
Fix extra right bracket
MinecraftForge / FML @ a8cbef2321a8e1bdfac56476bdfb5b306f71d38b Finally hopefully fully kills the race condition causing a classcast on slow machines .
Fix log version string .
added latest jar
Temporaly remove yahoo tests
Removed un - used p . paused ( ) .
LPS - 18065 Fix bad regen
updated min sdk to 11
Fix typo
add change
Add Q3 2011 ADL slides to docs / shareables / adl
return actual value of isLocal ( ) in command line args
LRDOCS - 2232 Remove unneeded property
Make 1 . 0 . 0 header the same level as others ( # 2885 )
add Alireza as contributor
added brew upgrade to MacOSX build instructions to avoid boost error .
Ignore patterns
fixed max size of library slots , close # 1710
Bump pegasus to 1 . 9 . 5
suppress warning
Make 1 . 0 . 0 header the same level as others ( # 2885 )
Add project_config to sdk module
Update the ptbtokenizer test to reflect the non - americanization
Remove unnecessary code
Add toString ( ) to IndexShardGateway
Build ' client ' target with - Wno - sign - compare .
Added back playInBackground property in js
Fix typo
turn off active by default on tests ( # 1843 )
Release pegasus 2 . 6 . 3 .
Only build tagged versions
force AST Injected property check with staticCheckerVisitor
test patched < gant > task and AndBuilder , that respects UnknownElements
update travis
Fix Test
Remove unused file
Remove the over quoting .
Fix build .
Removed obsolete macros .
Fix build
Fix test failures for CASSANDRA - 5175
upToDateWhen = false
Fix build
Fix log version string .
Return this instead of null in TimeoutStream # resume
mentioned hide offline feature in the changelog
Override bootstrap ' s th styles .
Remove unused file
Removed legacy icons in JB workaround app
added few known transitive verbs .
Removed old symbol pattern .
Delete proguard . jar
Fix typo
adding doc file
Remove unused file
Build fix
bump to version 1 . 5 . 2
Added Example apk
Adding maven central to build
Add forgotten static file robots . txt
add function with zero arguments
Upgrade oss - parent
we could be leaking file descriptors here
set IDEA JDK from build script
updated credits
Set oss parent to 9
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
Add a shouldUpdate property to nodes whose layout changed
Fix changelog
Fix Travis config syntax # 255
fixed compilation error
Remove extraneous semicolon .
FastArray doesn ' t overwrite toString ( ) method
fix conflicting native library error message
Fix build .
Fixed import .
Build fix
Fix build
Adding mavenLocal ( ) for local resolution
Removed PDF from what ' s deployed to the mvn repo .
LPS - 62799 Fix NullPointer in test
added Travis CI configuration .
update changelog for 1 . 1 . 1
missing method from desktop version
fixed test
Introduce internal ` server ` command
Delete truth jar which I forgot to delete when removing Ant support .
Changed email address for travis
Add missing method
Fix config
Fixed color
update Alipay and Weixin
added wiki images
Added support for automatic legend generation for Wheelchair renderer
update changelog for 1 . 1 . 1
Upgrade JUnit to 4 . 12
add overlay
Widen message list chip to better match message view .
update capture gif
Delete default README
add travis support
Add maven central repo to readme
Remove unnecessary code
LPS - 19211 Missed build . properties
Removed lib / .
fixed wrong project . properties
update slf4j version
Log stack traces of test failures to the console .
Fixed a subtle bug I happened to introduce last night .
correcting version to be really 1 . 8
Fix for issue 27
Added missing property for playWhenInactive .
remove empty duplicate AbstractEdge
Updated gradle release plugin dependency to 0 . 1
Fixed import .
Bump otto
Modified resources . arsc file to make some resources public .
Delete default README
Make executable
add gitkeep for assets
Remove newline at end of VERSION file
update windows natives
Set travis jdk to java8
remove todo
update windows natives
Set the correct version
Added OGNL expression object graph expression language jar
rename code style jar
Fix broken image
ignore " bin " directory ( created by Eclipse )
Fix changelog
Added database artefacts to .
Added support for automatic legend generation for Wheelchair renderer
Fix name of java executable
updated jsr166e to the 9 . 08 . 2015 version
fixed an error in the pom . xml file
Delete build . gradle
Remove unused file
Set oss parent to 9
Fixed import .
add toString for Fields
Prepare change log .
add the mavencentral repository on the root level
Remove unused file
Remove blank lines
Cache the contents of .
Prepare change log .
Fix checkstyle
remove todo
add function with zero arguments
updated to ignore merge leftover files ( orig ) and ant builds
Changed version
update xsoup to 0 . 2 . 1 # 75
Add missing method
prepare release HikariCP - 1 . 1 . 6
Fix data driven testing example in documentation
Add missing method
Set isInEditMode ( ) to true # 9
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
make Preconditions package private
Update SpongeCommon for DestructEntityEvent cause improvements .
Removed unnecessary return statement
Fix warning
Ignore patterns
added missing def
missing return in svg ' s getCoords
Added screenshot
comment out snapshot plugin for release
LPS - 65607 Export the concrete package .
Fixed validate IPv4 address method
Disable JS tests when enabling the profile dbTests
Prevent NPE in HardwareRenderer
remove analytics from alpha not enterprise
Added files via upload
Fixed bullet points in README
debug mode screenshot and miniature
improved handling for Droid Incredible 2
Prepare next release v1 . 0 . 1 - SNAPSHOT
Exclude JMH tests from coverage reports .
Fix build
Add text editor temporary files to .
remove debug output
Bump the version
Removed the .
add table of contents in python / README
remove a print
Created the AJAX Spider help documents , added it in penetest . html and also in the indexes .
Updated database
Update SpongeCommon for DestructEntityEvent cause improvements .
Upgraded slf4j - api from 1 . 6 . 1 to 1 . 7 . 2
Added dash to test push
update jars
updated studio
Updated jol to 0 . 2 to resolve the slow startup problem due to heavy GC
add table of contents in python / README
prepare release storm - hbase - 0 . 1 . 2
Moved compileSdkVersion and buildToolsVersion on top level build . gradle
Properly handle empty layout in getFirstVisiblePosition ( )
Move the wcursor increment after the assert
Fixed import .
fixed NPE in Box . extendToEncompass , close # 1783
Fix build
add overlay
Prepare change log .
Introduce internal ` server ` command
Remove temporary test
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
update changelog for 1 . 1 . 1
Bumping version name and code for 2 . 6 RC 2 .
disabled failing test
update refs
updated changelog for version 0 . 2 . 2
Add the isVisible ( ) getter
Prepare change log .
Fix broken image
Fix css
Updated gif
missing return in svg ' s getCoords
Updated icons to better comply with Android Developer Guidelines .
Properly stop server .
Remove unnecessary code
Made text_box_light have a white background
Add a new ' pre - checkin ' target to help keep checkins clean .
Fix wasInThePast
Added manual GLProfile shutdown to make sure that no JOGL threads are
Added Data Science doc to H2O - Dev docs site ( 1st new file )
Remove unused file
Remove obsolete file
Bumped wrapper version in the build file for consistency .
added OnionKit library import
Fixed missing information
Updated travis file for Java 8 & to notify me as well .
Setting build group and version
improved handling for Droid Incredible 2
Set the correct version
Fix typo
Remove unused link to libcutils
resolved conflicts for merge of fb2e3c8d to master
Remove unused file
LRQA - 16067 Add list of product names into test . properties
added support for AssertStatement
adjust hight
Fix syntax error
prepare for next development iteration
Added missing JNA jar
Added files via upload
set IDEA JDK from build script
add getCount method to BytesInputStream ( @ MysteryMachine )
Set the root project name
Added diffutils library
Update doc commit pointer for 0 . 3 . 2 release
add an accessor for the executor service
Fix for issue 27
Add new screencapture . dll for Windows 32 - bit .
fixed git ignore name
Moved compileSdkVersion and buildToolsVersion on top level build . gradle
Compile tests with source attribute .
Fix up formatting of header after branch
Remove ignored file
FredrichO - fixed spacing on the bottom of the number of columns in the media gallery settings layout .
Create circle . yml
Set isInEditMode ( ) to true # 9
Skip Hive tests under Java 6 , since Java 6 isn ' t supported by recent versions of Hive anymore .
Remove debug statement
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
remove mention of GROOVY - 6226 ( Configure Eclipse Plugin ) now that the issue is closed
Introduce internal ` server ` command
Repaired the conflict from wrongly uploaded jar file
Add xml declaration
Fix comment
Remove provided scope of support lib dependency in pom . xml .
updated studio
Fix build
Set the correct version
Include UPGRADING . rst in assembly
remove Fixtures . java to test , why was it in main ?
build make buildlog include tests run and fail stacktraces
Temporarily disable MixinC00Handshake
Add more fiels to gitignore
optimized imports
Bump common ref .
Prepare next release v1 . 2 . 1 - SNAPSHOT
Git hygiene
Add maven central repo to readme
update changelog for 1 . 1 . 1
Don ' t lowercase word vectors by default
added gitignore .
Set daemon flag on poller threads .
Fix build .
Set version to be 1 . 0 . 1 SNAPSHOT rather than 1 . 1 .
Exclude pom generated by shade plugin from list of modified files ( minor )
Updated build tools from OC JB workaround app
Corrected junit jar
keep deprecated requestFBOLayer ( ) method for now .
LPS - 63269 apply patch
updating to the latest jain - sip version
Fix # 1173
Upgrade rxnetty version to 0 . 3 . 13
add getCount method to BytesInputStream ( @ MysteryMachine )
prepare release storm - hbase - 0 . 1 . 2
Remove unused file
added ISchemableSpout interface
Add local . properties to .
Remove inspektr dependency version number since it ' s defined in parent POM .
added shippable builds
added phonegap icon to demo2
updated studio
only write diagnostics log files in desktop mode
fixed test
fixed compilation error
suppress warning
Add service definition so ServiceLoader picks it up
set IDEA JDK from build script
make Preconditions package private
Fix build .
Updating parent pom version of reporting to 1 . 3 . 0
Preparing for release 0 . 3 . 0
Added CLA pdf
remove unused resources
updating to the latest jain - sip version
Fix build .
Fix consumerProguardFiles by moving it to defaultConfig
add 1 . 8 changelogs
initial git ignore file
Remove test I opted to host elsewhere
Move GenericKmlBikeRentalSource to correct place .
Added Data Science doc to H2O - Dev docs site ( 1st new file )
Rogue line number for method declarations confuses IDE debuggers
Resolve bower dependency conflict , hang ( zeppelin - web )
added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
updated R notebook icon @ kevinushey
Remove NOPASS .
Fix profiler after module structure has been changed in pydevd , take 2 ( PY - 18442 )
ignored a few more IDEA files
Fix build failure
Remove debug output
Fix build .
Add logging of Bintray user for CI
actually run all the tests
Add travis ci
Fix memory leak
Set the correct version
Skip Hive tests under Java 6 , since Java 6 isn ' t supported by recent versions of Hive anymore .
prepare for next development iteration
Remove post tag in circle file to attempt build fix
Java regexps do support possessive quantifiers ( IDEA - 81507 )
Change the ignore file .
Updated code .
Prepare change log .
use underlying type for builtins
fix send as picture switcher vertical position in attachment modal
Introduce internal ` server ` command
update changelog for 1 . 1 . 1
Fix build .
Enhanced Windows installer images .
update build tools and target api
Move file to correct dir
add readme for sample app
added wiki images
missing break in switch
override canNavigateToSource for the future compatibility
Fix indentation and code style
Upgrade rxnetty version to 0 . 3 . 13
added few known transitive verbs .
build make buildlog include tests run and fail stacktraces
add context accessor for subclasses
Updated springsource logo
Ignore OSX and IDE files
updated min sdk to 11
Fixed import .
updating to the latest jain - sip version
Create README . md
Remove unused file
added example images of thumbnails
Updated gradle from 0 . 6 to 0 . 7
Move atari font notice out of res directory .
specify gradle version
Set minSdkVersion + targetSdkVersion via build . gradle
updated pac4j version to the released 1 . 8 . 2
add eclipse and idea projects to gitignore
Removed un - used p . paused ( ) .
Adding version
Fix Mock provider after merge of # 51
added travis file
Added a release_description file to be used by CI
Finished top level tool bar and misc fixes .
Updated Ant jar
added changelog for 1 . 6 . 1
revert icon to old one
added few known transitive verbs .
resize image
Add junit as a dependency for subprojects ( modules )
Fixed test for changes to ' model ' report output .
Fix checkstyle
uppdate build tools
set IDEA JDK from build script
Bump " demo " to 1 . 1
remove alert
fixed compilation error
Create img
FastArray doesn ' t overwrite toString ( ) method
Updated doc
updated JettyWebfilterTest . java to JettyWebFilterTest . java
Build fix
Cleaned the directory for .
Fix style on build . gradle
Returning proper type for config setting .
Prepare next release v1 . 0 . 2 - SNAPSHOT
Remove debug printout
Introduce internal ` server ` command
Removes the TODO to upload the library to bintray / jcenter
Remove test I opted to host elsewhere
updated sign stage
Updated changelog for 5 . 5 . 3 .
Modified url for issue tracking to directly show tickets for the component .
fix for GRAILS - 6503 " WAR does not include JARs from compile - scoped plugins "
Ignore OSX and IDE files
update android native
bump Android JAR version to R4
Fixed version .
remove waiting for device
Added public method to Cache to check initialized state
Fix testdata
Add images for the index file for the SpinnerTest test application sample .
Fix incorrect closing tag
follow / unfollow API
Move H2OApp into a package
Set the correct version
keep deprecated requestFBOLayer ( ) method for now .
add unistd . h for getpid ( )
Whack version that replaced unexpected - condition error condition with unexpected - request .
update gitignore with local . properties
add style images
fixed file name of travis script
Remove unused file
remove debug output
LPS - 66848 Add missing Gitignore
updated version
ignore swp files
Git hygiene
improved image for the docs
Remove extra newline
Added gitignore .
Fix checkstyle
Adding Read icon , updating Dashboard / Reload icons
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
add intention test to all tests suite
Updating linux bullet binaries
Remove unused var
Resize default xlarge wallpaper .
Cleaned the directory for .
Add missing method
Fix build
Remove unused file
Fix typo
Fix typo
add words
remove unused property
updated TODO
suppress warning
LPS - 45010 Fix typo
Removed DoubleCheckedLocking from checkstyle . xml .
Update doc commit pointer for 0 . 3 . 2 release
Fix typo .
add jekyll _site directory to .
dropped old and unused method
add table of contents in python / README
Updated CHANGES . txt
Prevent infinite loop on exception
fixed compilation error
add getCount method to BytesInputStream ( @ MysteryMachine )
Prevent duplicate loader onLoadFinished calls on config change
Removed unused import
Add eclipse plugin .
Added support for automatic legend generation for Wheelchair renderer
add getCount method to BytesInputStream ( @ MysteryMachine )
Number the reference
Removed old symbol pattern .
Bump common ref .
Bump the version
Revert " Reduced header size "
Reinstate view example for screenshot tests
Ignore lint warnings for unregistered activities
Reduce the amount of logging from the Javadoc plugin .
Ignore OSX and IDE files
Updated changelog for 0 . 8 . 3
set the correct version for the branch
Remove empty line
Fix for issue 27
Fix Makefile to not automatically install node modules
LRQA - 16067 Add list of product names into test . properties
Adding bin related files to gitignore ( # 130 )
Remove unused constant from TWLayoutManager
GROOVY - 4440 fix Apple ' s L & F detection when running Jdk6 +
Don ' t automatically show the batch buttons when entering multiselect mode
Prepare change log .
bump Android JAR version to R4
Hebrew uses language code iw apparently .
remove unused method
Updated ignore file
die extra plugins
Fix Portuguese docs navbar
Remove blank lines
Removed minSdk Call
LPS - 62799 Fix NullPointer in test
updated to ignore merge leftover files ( orig ) and ant builds
Ignore Vim / Vi backup & swap files
Enabled Vertical ScrollView instrumentation test in SandCastle
Upgrade maven - javadoc - plugin to its latest version 2 . 9 . 1
remove unused resources
Add caching of Maven artifacts to Travis CI build
added tablet screenshot
add 1 . 8 changelogs
Fixed the module name
Adding image folder for Flow documentation graphics
Fix build
Fixed typo
Remove blank lines
remove a wrong char " 7 "
Remove < pre > borders in result frame
Add vcs root
Not using any more
Remove superfluous Ahem . tff
Fix cloud status availability from old URL ( v1 ) .
Removed the blue outline from the whiteboard buttons that are selected .
Fixed pom . xml tag
Create Jar artifact with test code
add unistd . h for getpid ( )
Updated build . gradle for maven
add eclipse and idea projects to gitignore
Fix signing fallback .
disable tests to obtain a cache
Add jar built by Oracle 1 . 6
Added screenshot
Set the correct version
Fix build
Fix package in manifest
Removed bottom margin of buttons at the bottom
Add product flavor to reduce build time on debugging
Moved assertThat ( ) back into hamcrest - integration ( really this time ) .
Fix build .
bump socket . io
Fix resources
Ignore gradle related files .
Bump otto
remove jni . h include from IOMX . h
bump to 1 . 7 . 6 and minor CHANGELOG cleanup
Added Data Science doc to H2O - Dev docs site ( 1st new file )
suppress warning
Make 1 . 0 . 0 header the same level as others ( # 2885 )
HHH - 3580 added entity manager to module list
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
Make Tachyon - Perf a subproject of Tachyon
update CHANGES
Moving class to dp package
Added auto unit testing
prepare for next development iteration
Prepare change log .
Remove Notification Center observers on dealloc
deleted tools . jar
Use new sanitizer option .
add in missing module traceback
set IDEA JDK from build script
Update the ptbtokenizer test to reflect the non - americanization
LPS - 56049 Set default project group
Create webapp / llap directory for MiniLlapCluster
Fix build
added kmtoy for ex
Remove unused import
Ignore OSX and IDE files
jetty - 9 commit test
Get me out the stupid readme file .
disable tool
Add TODO
MinecraftForge / FML @ e3ce211cc798f4d86ca6f974d9ba8b4e389b4dc9 Nullcheck the dispatchers on players .
Fixed deprecation
Updated build . gradle for maven
The / green command should now only affect dirt on the top layer .
remove repeat lefover . . .
Fix stupid copy / paste typo .
Remove unused import
Fix build
updated JettyWebfilterTest . java to JettyWebFilterTest . java
Ignore OSX and IDE files
Make Tachyon - Perf a subproject of Tachyon
Moved logging configuration to the PC Facade where it belongs .
fixed typo in changelog
add function with zero arguments
update slf4j version
Added the legend to the bottom of the graph .
update pom . xml
Removed some unnecessory code
Fixed import .
Fix data driven testing example in documentation
Remove test I opted to host elsewhere
reenable daylight saving test , now that we use joda - time 2
assign success variable a value
Ignore OSX and IDE files
meteor / AWSCloudFormation added to validation list
remove PIDFILE at stop time
Write checkstyle to stdout .
build make buildlog include tests run and fail stacktraces
Add callback for ` add ` ( Android )
Fix data driven testing example in documentation
Add a .
set version
prepare for next development iteration
Actually fix dupe drop
Fix file name of DeepLinkRegistry and its test
Tweak gitignore .
Fix warning
alternately patched avro jar
Update doc commit pointer for 0 . 3 . 2 release
Remove old comment
disable bounds checks on release build for samples .
Prepare change log .
removing the pxfetcher module from the gradle settings
Add intellj project files to .
Add isClosed in DruidDataSource
add abortOnError false - so that clean build runs without a problem
EftarFileReader . close ( ) cannot throw exception
Remove the over quoting .
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
added a little padding to table cells to improve look and readablity
Add missing method
Updated gitignore to ignore hprof files
Set width of drawer to 320dp
updated 2 . 0 and 3 . 0 plans
Added oraclejdk8 and openjdk8 to the set of CI JDKs
Fixed import .
add new asset for Swagger
regenerate gradle - wrapper . jar with 1 . 9 - rc - 4
Make 1 . 0 . 0 header the same level as others ( # 2885 )
set IDEA JDK from build script
Fix wrong file name
Bumped up parent pom version to solve custom checkstyle issue
reduce T * Map , T * List memory consumption for empty collections ; just like ArrayList did in JDK8
Start 1 . 4 . 2 version .
Add missing import to chapter six example
Make hadoop directory .
ignore class files in root ( which are generated by " gradle test " )
Fix filename typo
Updated copyright date in LICENSE .
suppress warning
Ignore OSX and IDE files
Bumping up version to 1 . 0 . 1
Remove newline in TicTacToe example
prepare release astyanax - 0 . 8 . 10 - SNAPSHOT
Fix build
add blob docs to index
Prevent duplicate loader onLoadFinished calls on config change
add abortOnError false - so that clean build runs without a problem
Fix permissions
update linux amd64 natives
Ignore OSX and IDE files
Updated TeraBullet with fixes to Rigid Body < - > world collisions
Add State and InputStream to the IRecognizer interface
updated gradle wrapper to 1 . 10
Added support for travis - ci
Set isInEditMode ( ) to true # 9
Remove unused file
Ignored eclipse project files .
Remove unused imports
Remove NOPASS .
Fix build .
add temp directories generated by zeppelin - Rinterpreter to gitignore
comment out snapshot plugin for release
remove log4j jar from lib
Ignore bin and gen
Add maven central repo to readme
update changelog , release version to 1 . 5 . 10
LPS - 51912 remove redundant ` continue ` keyword
update logback 1 . 1 . 3 - > 1 . 1 . 5 ( closes # 272 )
Bring the children into the project .
Added parsing of Cython typedefs
Add images for the index file for the SpinnerTest test application sample .
remove unused jar
Fix build .
Add Small ignore files
disable reloading for scripts with dates in the future
Changed field type of username in jiveGroupUser .
Replaced derpy tabs with spaces
Updated the .
Move the wcursor increment after the assert
add res directory .
Moved AstBrowserProperties from src / main to src / resources .
improved handling for Droid Incredible 2
Fix bitmap tinting
add getCount method to BytesInputStream ( @ MysteryMachine )
Add local . properties to gitignore
correct null + String to not throw an NPE
Added gitignore .
Remove this configuation manipulation b / c it ' s unnecessary .
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
update xsoup to 0 . 2 . 1 # 75
Includes changes to GroovyClassLoader regarding getLoadedClasses method .
Remove temp files
Exclude pom generated by shade plugin from list of modified files ( minor )
Remove mistakenly added module reference .
Disable JS tests when enabling the profile dbTests
Rename Filter to FilterActivity to prevent name collision
Add microbench to the module list
update changelog for 1 . 1 . 1
Prepare next release v1 . 0 . 2 - SNAPSHOT
Added Travis
Add robolectric cache to gitignore
set version to 4 . 5 for release ( hopefully )
Fix build .
Add package . html .
Fix build
ignore this
add jamm - 0 . 2 . 5 .
set IDEA JDK from build script
cm changes broke this
Fix Groovy - 226 .
FastArray doesn ' t overwrite toString ( ) method
set the version
Add missing method
removed music . ogg from pax
Prepare change log .
missed file ?
use the default junit version .
Add Eclipse specific project files to ignore .
Make test NOPASS .
Move H2OApp into a package
Removed unused file .
Add * .
Add a .
added info option to travis to output more information
add eclipse and idea projects to gitignore
prepare for next development iteration
add eclipse and idea projects to gitignore
updated 2 . 0 and 3 . 0 plans
Include generated grammars in source zip for debugging purposes
Ignore target directories
Build and install the tests jar artifact
Turn off baseline aligment in wide show info layout .
Finish removal of pages submodule
Removed Key Value Server from SVN repository .
set the correct version for the branch
remove dependency on react - native which will break the packager
Removed new lines
Move rebalance scripts to bin directory
Fix build
Update doc commit pointer for 0 . 3 . 2 release
set IDEA JDK from build script
add context accessor for subclasses
Set minSdkVersion + targetSdkVersion via build . gradle
add abortOnError false - so that clean build runs without a problem
Ignore gradle properties file .
Make the gradle wrapper executable .
updated icon from Vincent .
LPS - 45010 Fix typo
Parallelize the core tests .
Remove blank line
LPS - 62799 Fix NullPointer in test
Updated CHANGES . txt
updated library
update refs
Fix build
add eclipse and idea projects to gitignore
Bumping version to null
Fix issue with state reset
Upgrade Ivy 2 . 2 . 0 RC to final
update changelog for 0 . 9 . 0 - rc1 , prep for rc2
Fix build .
Remove blank lines
Fix PyCharm edu icon
add MavenCentrail ( ) in allprojects of build . gradle
bump version for 0 . 9 . 0 release
Fixed import .
Add missing method
Fixed typo
disable tool
remove unused import
Prevent duplicate loader onLoadFinished calls on config change
give access to the defining classloader
Add mongodb service for travis config
Remove files from obolete and unused figures
fixed ExpandoMetaClass inheritance and allowed changes to any class used Object . metaClass syntax
Add ulimit printing to travis .
uppdate build tools
Push a AHC Quick Start Guide
Prevent duplicate loader onLoadFinished calls on config change
set the version
removed commons lib since now it ' s part of svn repository
Add project files to .
Updated CHANGES . txt
add new default material images
FastArray doesn ' t overwrite toString ( ) method
Set proper release version
Remove Y
bump to version 1 . 5 . 2
started core project
FIX Dashboard always display a scroll in IE7 ( cherry picked from
help ID ( IDEADEV - 34211 )
update jars
add uaa classpath to eclipse classpath
Bump the version
remove todo
add site as a submodule
Bumped up parent pom version to solve custom checkstyle issue
Ignore OSX and IDE files
learning git
Fix typo
Fix xhdpi box
fix up test case
Added auto unit testing
fix wrong name
Added more task to the set of tasks triggered by Travis CI .
change default request connection timeout to 3 secs
Permit the folder list item to expand vertically .
Remove unused file
Improved performance for isPresent for windows
Prepare change log .
Rename no . properties to nb . properties
remove log4j jar from lib
added scripts to create heron - tools self extracting binary
missing fields for automcompletion
added Kasper to list of developers
added link to issue
set the version
Ignore IntelliJ ' s .
Fixed import .
Renaming pom artifact - id , so that gocd shows up instead of main ; when opening up multiple projects in idea .
deleted tools . jar
update changelog for 1 . 1 . 1
set the version
remove unused source file
remove unused method
add abortOnError false - so that clean build runs without a problem
removed dependency - reduced - pom . xml from .
revert committed configuration
Updated the .
Added gitignore .
improved image for the docs
Disable mocking " promise " in OSS Jest tests
Add handler for download event
change the permission of make . m to 644
Remove redundant entries .
Added files via upload
add context accessor for subclasses
Prepare next release v1 . 0 . 2 - SNAPSHOT
Create a Plugins . sbt file for required build plugins - currently just the sbt - pgp plugin .
changed publishJavadoc task from Copy to Sync
Git hygiene
debug mode screenshot and miniature
fixed description
bump to version 1 . 5 . 2
update windows natives
ignore IntelliJ files
add style images
prepare release checkstyle - 6 . 11 . 2
Add missing method
Set isInEditMode ( ) to true # 9
remove mention of GROOVY - 6226 ( Configure Eclipse Plugin ) now that the issue is closed
Making default Socket timeout 20s ( from 8s ) .
Added toString ( ) method in NeoApp . NeoAppRelationshipType . . . otherwise
Write checkstyle to stdout .
Updated code .
Added run target .
Revert parts of the .
Remove extra newline
updated sonatype parent pom version from 7 to 9
Log test errors .
updated version
Delete truth jar which I forgot to delete when removing Ant support .
Update doc commit pointer for 0 . 3 . 2 release
Added files via upload
Remove unnecessary code
Fixing GLIBC 2 . 4 problem on Debian system .
Removed some unnecessory code
Print current running unit test in pulsar - broker ( # 57 )
Fix style on build . gradle
Bump the version
build make buildlog include tests run and fail stacktraces
Prepare change log .
ignore screenshots from tests
update CHANGES
edit screenshots
Fix build
Remove unused import
suppress warning
remove empty file
Excluded testNg until Gradle migration is ready .
Start 1 . 4 . 2 version .
Configured surefire to use UTF - 8 so that Aslak can write & read his
Removed unused images
Bigger moving average range in importer
Updated changelog and contributors file
update javadoc
Set the correct version
remove unnecessary config properties
Added 5 new biomes as included in MC 1 . 1 as part of # BUKKIT - 496
Drop cached qualified name after changing nodes in subtree
removing empty lines
Updated code .
Adding * .
Removed old symbol pattern .
add deskshare folder
update dict
Add ignores for idea and eclipse project settings
Correct a typo .
udpated the read me
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Remove unnecessary code
Fixed proguard issues
updated screenshots
update wiki
make dummy change and assert CC is updating correctly
LRQA - 16067 Add list of product names into test . properties
Update the ptbtokenizer test to reflect the non - americanization
do not show gpx export items at start
Release pegasus 2 . 6 . 3 .
Fixed color
Build fix
Fixed static use for tic 323
Resize default xlarge wallpaper .
Fix enforcer rule for java 7
Invalidate ActionMode content rect on scroll .
add jamm - 0 . 2 . 5 .
Remove unused file
Increased RCTInlineValueThreshold for asynclocalstorage
Fix data driven testing example in documentation
Removed large unused images
remove useless annotation
improved handling for Droid Incredible 2
Adding more temp files to gitignore
adjusting changes . txt
Ignore OSX and IDE files
LPS - 63269 apply patch
Include lib / instead of libs /
Removed DS_Store files
Added toString ( ) method in NeoApp . NeoAppRelationshipType . . . otherwise
Prevent duplicate loader onLoadFinished calls on config change
add eclipse and idea projects to gitignore
Fixed static use for tic 323
add changelog for June 2015
Fix for issue 27
Ignore IntelliJ IDEA files
added intellij specific file to .
Fix changelog
Update build branches
add eclipse and idea projects to gitignore
Removing return statement so that the adapter always reloads the posts list after a post fetch .
Added checkstyle to core and cache module
Delete a local ref in getSurface
Added missing JNA jar
Remove unused file
Updated doc
fixed broken test case
Removing swp file
Remove circleci config
Added volley . jar to the project
moved TestNGListener from src / main to src / test
Set jdiff version
Set minSdkVersion + targetSdkVersion via build . gradle
updated version number
Releasing v8 . 0 . 5
adding build and lib folder while ignoring their contents .
build make buildlog include tests run and fail stacktraces
Ignore OSX and IDE files
Updated the zip file .
added gitignore to blob
update changelog for 0 . 9 . 0 - rc1 , prep for rc2
Remove comment
Updated Ant jar
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
comment out snapshot plugin for release
Add pointer to h2o - 3 repo .
fixed typo
Updated help jar prior to weekly release
Update doc commit pointer for 0 . 3 . 2 release
updated credits
do not show gpx export items at start
Remove NOPASS .
update factory images
Remove unused file
updated distribution . xml to include whirr recipes and configuration files .
LRQA - 16067 Add list of product names into test . properties
Ignore patterns
do not show gpx export items at start
Give a useful error message when the neo4j shell script gets no command
update the project
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
bump to version 1 . 5 . 2
preserve generics parameters when create methods for parameters with default values
Add missing method
Add a repository block to library only section . . .
Fix the build
Make 1 . 0 . 0 header the same level as others ( # 2885 )
fixing warning
Remove assets which are no longer used .
LPS - 44121 Add support for internal type in SDK
Testing Circle CI
set IDEA JDK from build script
CHanged target build sdk for osmand
Fixed import .
upgraded guava to 20
added package . html
Remove unnecessary code
update maven - release - plugin to 2 . 5 ( fixes issue where release fails to tag properly )
gh - 425 - added empty context xml file to rest api
Delete obsolete icon
fix wrong name
Set version of gpg plugin .
Fixing null values in first domain trust array entry
ignore mac finder droppings
MinecraftForge / FML @ d00feb58c762b0bbc506d79faf1ce40bc96732e9 Remove debug code that was causing console spam in Forge .
remove extra line
Add a META - INF / services file specifying JimfsFileSystemProvider as a service provider .
Require Maven 3 . 0 .
optimized imports
Set proper release version
Fix mCoveredFadeColor setter
Fix build .
add function with zero arguments
build trove4j to be compatible with 1 . 5
using gradle
updated min sdk to 11
added info option to travis to output more information
add a blank line to try and test github webhook
Removed unused import
Delete the localrepo .
LPS - 64187 update package info
Finish removal of pages submodule
Fix build script for generating md5s
Fix build .
update changelog for 1 . 1 . 1
Set bg and fg colour in site . css
Use Java 7 on AppVeyor
Moving changelog wikipage to AsciiDoc
add eclipse and idea projects to gitignore
Delete truth jar which I forgot to delete when removing Ant support .
updated pac4j version to the released 1 . 8 . 2
Updated build . gradle for maven
STORM - 751 Move javadoc aggregate to site phase .
Introduce internal ` server ` command
ignore * .
update windows natives
Remove extra newline
Fix un - updated rule change
Use newer sonatype pom .
Fix OF - 654 - Limit index size of JID to 256 for mysql
Add unzip as a dependency
updated sonatype parent pom version from 7 to 9
update windows natives
add getCount method to BytesInputStream ( @ MysteryMachine )
trim some fat
Use new sanitizer option .
Updates
Add margin clear button
resize image
Add solid shadow .
add html attribute
Fix build .
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Added missing JNA jar
MinecraftForge / FML @ c48b48ee15f38d3e794b6eb3499c536226ca5a79 Fix server launching .
Fixed static use for tic 323
updated sonatype parent pom version from 7 to 9
fixed the build
Updated project . proerties to build with latest SDK .
Releasing v8 . 0 . 5
fix compile error
Updated Ant jar
Add config for Travis CI
Added files via upload
Make notest .
Begin development of 1 . 11 .
missing icon
Delete build . gradle
remove newline
Fix crash on Windows x64 when receiving video , add native Windows video renderer for 32 - bit and 64 - bit .
Set the correct version
ignore all classpath / target / .
Remove extra newline
Added translation using Weblate ( Polish )
remove warning
remove blank line
Added John Wagenleitner to the contributors
updated credits
Remove unused file
Fix release number
Update uploads view when finish upload is deleted
Fix build
ignore IntelliJ files
disabled failing test
Add platform - tools to .
trim some fat
updating to the latest jain - sip version
- Incorrect link in " Break tab " help pages
add JSR 305 annotations jar
Fix check for ANDROID_HOME environmental variable
Stop Gradle from destroying IntelliJ project settings
update build . gradle
Add fatter divider on xhdpi devices .
Return the record state locked
Added React import to android VideoPlayer Example
Updating README .
fixed typo
add iframe option
Avoid infinite loop
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Fixed import .
Added VIM temp files to gitignore .
using bash specific syntax , so should declare rith shebang . . .
Updated gitignore to ignore hprof files
add seaborn to requirements . txt
Added support for automatic legend generation for Wheelchair renderer
Remove test I opted to host elsewhere
Moves stray java test class from top level project into pig module
Fix css
prepare for next development iteration
LPS - 58931 Move the media wiki zip from portal to its bundle
Not using any more
Fix a test using model report after making binary tasks visible in the model space .
Fix typo .
Remove unused file
Bump pegasus to 1 . 9 . 5
add blob docs to index
Remove obsolete file
Added a id to thumbnail + maincontent layout
Remove unused import
Moved logging configuration to the PC Facade where it belongs .
Shrink notification area to contents
added few known transitive verbs .
Updated version
Set oss parent to 9
Fixed typo in the changelog .
Ignore OSX and IDE files
help ID ( IDEADEV - 34211 )
debug mode screenshot and miniature
updated images for checkboxes and pagertabstrip
textIsSelectable = " true " to comment detail
Use the correct language code for Korean
Ignore OSX and IDE files
set the correct version for the branch
Fix an example of Tree model JSON output
reenable daylight saving test , now that we use joda - time 2
Fixed incorrect value for ChatColor . BLACK ( was 1 , should be 0 )
improved handling for Droid Incredible 2
updated font file
Move groovy . icns to lib
add release notes
Upgrade ASM to 5 . 0 . 2
Fix for issue 27
Start 1 . 4 . 2 version .
fix the misleading model_key name
Update SpongeCommon for DestructEntityEvent cause improvements .
update windows natives
deleted unused changelog
Bump gherkin
Fix build
remove log4j jar from lib
Add file local variables to build . xml
do not show gpx export items at start
update linux - arm native
Fix DRF / GBM tests - Gaussian deviance now works .
update jacoco to 0 . 7 . 0 ( IDEA - 123499 )
Fix build .
Added John Wagenleitner to the contributors
remove blank line
removed dev import .
Make 1 . 0 . 0 header the same level as others ( # 2885 )
Delete help button from postfix completion configurable
fixed ExpandoMetaClass inheritance and allowed changes to any class used Object . metaClass syntax
Added toString ( ) method in NeoApp . NeoAppRelationshipType . . . otherwise
disable tool
Use netty - 4 . 0 . 17 .
Removed @ Ignore from a passing test .
Index Update Settings API does not update settings in real time , closes # 1807 .
Ignore target directory
add Archive keyboard shortcut to MessageList , refs issue 3
Build ' client ' target with - Wno - sign - compare .
remove final
Add notification icon for use with Android 1 . 5
Prepare change log .
Fix Travis
Fixed static use for tic 323
Fix style on build . gradle
Bug 4588114 - Make GestureDetector behave nicer with parallel multi - touch detection
Missing Icon files .
Fix build
Update SpongeCommon for PlayerChangeClientSettingsEvent posting fix
Make the gradle wrapper executable .
Introduce internal ` server ` command
Ignore OSX and IDE files
Ignore OSX and IDE files
commented out a failing line
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
prepare for next development iteration
Added a gitignore
Properly handle empty layout in getFirstVisiblePosition ( )
Add Eclipse files to .
Add Maven artifacts to .
Add images for the index file for the SpinnerTest test application sample .
Removed Merriweather light variation assets ( since they won ' t be used )
Move test data file to correct location .
add a - d flag to dpkg
Don ' t show strange exceptions on shutdown ( PY - 5417 ) .
remove unused method
keep deprecated requestFBOLayer ( ) method for now .
Fix warning
update CHANGES
Removed new lines
Fix typo
Fix data driven testing example in documentation
Adding a previously forgotten resource to git
prepare for next development iteration
Set the correct version
Bump Spongecommon for EnderDragon Respawning fixes .
update refs
removed querydsl - scala / .
Fix build
Remove unnecessary dependency
LPS - 52060 update sdk
No longer skip integration tests on Jenkins
Fix changelog
Added symbols . macosx .
update changelog for 1 . 1 . 1
Fix test failures for CASSANDRA - 5175
LPS - 44121 Add support for internal type in SDK
remove unused method
LPS - 27200 Jetty needs JNDI
Bumped JadConfig to version 0 . 3 , fixes SERVER - 59
ignore content generated by grunt
Fix typo .
Ignore reports directory .
Remove a spurious symlink
missing icon
Add some gitignores
reset version for development
Exclude pom generated by shade plugin from list of modified files ( minor )
build make buildlog include tests run and fail stacktraces
fixed compilation error
build make buildlog include tests run and fail stacktraces
Fix bug 3425610 Adjust Lock sound level
add iframe option
Remove NOPASS .
Update build number and version name for 2 . 6 beta 1 .
Remove empty line
update changelog for 0 . 9 . 0 - rc1 , prep for rc2
remove libsvm . jar
do not show gpx export items at start
Moving changelog wikipage to AsciiDoc
Adding sample pages to web - service
Generate XML reports from JUnit test reports
build make buildlog include tests run and fail stacktraces
Add gitignore
Publish gradle - logging artifacts
Add missing import to chapter six example
add words
Fix typo .
Ignore all .
Added toString ( ) method in NeoApp . NeoAppRelationshipType . . . otherwise
Don ' t run emulator and exclude github pages for builds
Fix build .
Removing legacy dependencies
update thrift jar to current recommended revision
Downgrade Hamcrest matchers .
Build and install the tests jar artifact
build make buildlog include tests run and fail stacktraces
Fix build
updated version number
Moving STUN sources from Openfire codebase to plugin .
Suppress warning
Remove blank lines
Adding Client Load - Balancing diagrams
mention 5950 in NEWS
Disable break on lint error .
update changelog , release version to 1 . 5 . 10
LRQA - 16067 Add list of product names into test . properties
Added files via upload
Create img
Fix solaris build
Ignore OSX and IDE files
Set the correct version
Add missing < limits . h > include
changed a typo from SHNAPSHOT to SNAPSHOT = )
Added grails central plugin repo back in as a dependency repository .
build make buildlog include tests run and fail stacktraces
Removed @ Override flag from compareTo method , since it isn ' t in the superclass .
Make 1 . 0 . 0 header the same level as others ( # 2885 )
Upgrade rxnetty version to 0 . 3 . 13
Bump the version
Added StatefulPersistenceContext . getProxiesByKey ( ) ( needed for testing non - flushed changes )
Build the JNI lib as a dependency rather than packaged
fixed memory leak
Add toString ( ) to IndexShardGateway
Find - > Search
Fixed bug of disappeared rounded angles after first display
rename dir
fixing syncDoc task to avoid up - to - date message only because target directory already exists
removing extra lines
added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
improved handling for Droid Incredible 2
updated version
Add State and InputStream to the IRecognizer interface
removed System . exit ( 0 ) from RunTests
remove old cmd option from usage sysnopsis
Set minSdkVersion + targetSdkVersion via build . gradle
keep deprecated requestFBOLayer ( ) method for now .
Moved logging configuration to the PC Facade where it belongs .
add style images
Fix fbthrift script
MinecraftForge / FML @ 570faeb790745c35403c67fabab57651b71da576 Added the ability to save transformed classes to disc for debugging .
Fixed static use for tic 323
move sql reference and rest documentation at end of ( sub - ) TOC
Putting tests in correct location
Bumped docs version to 2 . 5 . 0
missing colon
Change the flowdock notification for Travis builds .
Set animation to null after canceling current anim .
adding shim . R to description
Ignore OSX and IDE files
temporarily disable test
Add project_config to sdk module
Set proper release version
Updated library name
Add vim swp files to gitignore .
update weex - transformer to matched version
Log test errors .
