Fix snapshot version
Added joscar JAR .
Fix TsExtractor tests
Fix typo in README . md
Updated the version string to the version of T4J
Updated webchat logo - added oracle logo as a separate image
LRQA - 17074 Modify java . jdk . type property from x64 to x32
update fonts
Remove fonts from sysui package .
prepare release v1 . 4
update travis conf
Fix indentation
Set Gradle project name for CI
Set min width for add dialog .
Remove ignoreSnapshots , we no longer use snapshot of Commons JCI
Clarify prev / next Meaning
update travis config
run Findbugs on main only ( # 4131 )
removed unused line
Create CHANGELOG . md
Added Screens
bump up druid version to 0 . 4 . 0
updated examples
added conditions section
excluded netbeans path and building paths
Prevent insanely long passwords from crashing SystemUI
change _username_ field input type in NUX sign in
prepare for next development iteration
Fixes a crash of the QTKit video CaptureDevice on Snow Leopard reported by Yana Stamcheva .
Skip tests pending resolution of JBAS - 8339
Require Maven 3 . 1 . 1 or better
remove logall since it doesn ' t trigger anymore
Delete model - comprehension .
adds TODO for instantiateCroutonView
Fix typo in the android section of concept / buckconfig
Add travis
Add Review Board support .
adding missing library
Fixed problem with getHighestFnScope method
Bump parent pom reference .
Bumped gradle plugin
Rename README to README . md
Missing test data file
include missing dep for now
Bump the version
Fixed method signature
Delete tablet . png
Revert " Remove stale import "
Setting default name for multi - project
Changing Error to Warning
Updated the version #
Fixed bug in getType
Set javadoc encoding in utf - 8
Update CHANGES , Added 1 . 1 . 1 version notes .
Try different sources setting to attach and deploy sources artifacts
modify travis configuration to run embeded tests
Add some .
Fix typo in pom . xml
removing failing / missing module
Remove allowBackup property from manifest
Remove duplicated bolts library
Remove forgotten CLI module reference in parent pom
Corrected test data
replace demo image
add missing test data
Removed the 3 . 5 . x branch .
Add internet permission
Add gitignore
removed aapt since BuildHive didn ' t work
Remove stray import of java . util . List
improve gitignore
updated gradle wrapper to 1 . 6
missing import
Generate wrapper with 2 . 7 - rc - 1
prepare release deeplearning4j - parent - 0 . 0 . 3 . 2 - SNAPSHOT
run spark - submit command with bash - c
Fixed version number
Updated project . props to Lollipop
Fix # 47 - Update docs
using glassfish - integration instead of glassfish
Fix typo which cause stack overflow if children ( ) was called
Added instructions on how to build the files from ndk
Add placeholders into required ( by Android tools ) folders .
Fixes
Fix compilation with - Pyarn
removed the NOPASS flag from glm weights test .
adding logback - test file ( disable logging in tests )
Marking the Settings ContentProvider as singleUser
added info for forked - path workaround
Adding basic metric support
Add more locations to gitignore
removed echo
adding las vegas wav file
Move framework tests into correct package
removing binary jars
updated favicon
Fix Proguard flags causing crash in system bar .
Remove unneeded version property .
Added test - output to .
prepare for next development iteration
Fix doc for eclipse profile generation
tweaked sign on dialog
update maven dependency plugin
Update build tools to 21 . 0 . 2
removed comment
Added eclipse specific files / folders to .
Resolve conflict with filesystem package
missing AndroidManifest . xml
Put back abstract version number
Updated license date
Fix attribute reference in README
remove unused import
Reconfigured cobertura plugin to produce XML and work with coveralls plugin .
Removed groupId ( duplicates parent ) .
add download source of demo
Removing targetSdkVersion from library .
fade scroll bars for status fragment
Added min SDK version to AndroidManifest . xml
remove keystore
Adding building web placeholder
remove useless .
Fix readme about usage .
added the new icon to this repo as a place to host it
adding ignore file again
Add a note that states that you have to use @ Qualifier instead of @ BindingAnnotation in order for the generated code to work correctly .
remove custom project site css .
Make advanced view persistent .
add google repos
disable animation
prepare release storm - hdfs - 0 . 1 . 1
Fix filename
Added lib folder to ignore
Added jna platform jar .
travis only build master
Removed " target " entry from gitignore , allowing to commit changes to the " org . springframework . aop . target " package
Ignore Android Studio build output
Remove unused pic
fixing warning message layout size
Added a " docs " convenience task
Added Icon
Add a quick icon for the toolbar ( Just modified the executeCode . png file )
test coverage ignore private constractor
Add billing activity to manifest
Skip cobertura for releases
Close the HTTP connection in the callable
inadvertently removed method
Add Test Plan to Repo
Testing Travis - CI workaround
chmod 644 all drawables
Create README . md
Fixed problem with getHighestFnScope method
Added deprecated note
Fix phrases
revert log4j change , again
OSGi support - I forgot the ant task driver .
adding IntellJ logo
fixing gitignore
Remove accidental import
Ignore Mac OS X filesystem metadata .
Added files via upload
Updated material design icons ' .
improved screenshot
Add xxhdpi info window asset .
Delete gradle . properties . example
made javadoc classifier maven standard
remove " final " modifier for EventBus
update travis for jdk8
Added one line of space before main screen footer .
Allow external file picker
add the the previously deleted build - tools .
Fix SortedSet cqlsh formatting ( follow - up to CASSANDRA - 10513 )
prepared for next development iteration
Change action item min width to be 45dp which will make the smallest size a square .
Add SuperFinalize checkstyle rule
Fix parentheses balancing in README
Added fork .
SONAR - 5329 - Added activity table to DatabaseVersion for cleaning .
git ignore netbeans project configuration files
and fix a typo in the one line change
Rename observations doc file
Fix audio preprocessing library wrapper
Fix package name
Make dump - po - files .
Compiled libvudroid for arm64 - v8a for devices such as the HTC Nexus 9 .
Added missing newline at end of file
removing Gradle output that should not be in git
Add github ' s action bar icon
fix bug in non - choreographer looper
bumped version
Updated the Google search scenario as the original text is no longer shown
Fix typo
Adding caching to Travis
update travis
Remove bogus symlink .
prepare for next development iteration
updating gitignore
Moved utility class to the correct package .
upping the version to 2 . 0 - BETA
added support for file encoding
Fix the merge for forge
add Yan to team
Fixed bug in new entity sound hook .
Bump android build tool version .
Add slash to path .
Increases the amount of supported waving blocks to 16 .
Upgraded target versions
Removed bin from .
help ids
Set jdk version to 8 .
LPS - 57968 Add action to auth . public . paths
support single backslash tex math
Reverted changelog
set default profile dev
Disabling JaCoCo by default
Squelching the noisy travis per discussion in irc
Fix test
add version + 1
renaming UAParser . php to uaparser . php
Fix a bug for users with space in home path .
wait more and push more elements in to flume
Fixing broken image
arrange the sub - task order of clean task in order to execute cleanLocalMavenRepos task at the end .
Propagate constant name / version to magic property name / version .
Create README . md
Add correct mvn version to travis . yml
Add build number to archive name
added a copy of the exe file to cvs so that ppl don ' t need all of gcc to
Include a little reminder that you can put init scripts here .
Add travis .
Remove invalid generics from warningsOverload group .
Add Travis config .
fix a little annoyance , ignore emacs interlock files
add maven - surefire - plugin encoding
Bump version in instructions
Add options . setTrustedStrings ( true ) to ant jscomp
moving back to servlet 3 . 0 . 1 as 3 . 1 . 0 requires jdk7
Remove unused field from AssetManager .
add custom elasticsearch repo on google code
Force a difference in the timestamps by sleeping for 1 millisecond .
adding acls
Fix build break
Fix config
Prepare next development version .
Do not need regex anymore .
Use correct ' beta ' icon .
Add icon files for neo4j - desktop
Fixed path issue
Groovy Test module has a runtime dependency onto the " Ant " module for tests
Create README . md
Remove deprecated nodeprobe link
set default srcdir as delivered by the OSOLopengrok package
add configuration file to configure Tachyon Version
remove superfluous ` after " mvn clean validate - P checkstyle "
Add " Seashore " graphic file for " Feature Graphic " image .
Added tag 0 . 0 . 6 for changeset 9361e645790f
Add new buildout dirs to gitignore
removed obsolete Gradle files
LPS - 69838 Add empty property
Fix WebView automaticallyAdjustContentInsets error
removed unneeded file
remove example module from parent pom . xml
Upgrade release plugin
Create README . md
Remove executable flag from source files
Keep tmp / cache .
ignore all hidden file in linux .
Multi - Window support added for android N
added JUnit
patched version of itext 1 . 3 to include fix for osx
Fix missing Date import in Restore . java
Add missing comma
Activated execution flag on synch . sh ( # 2025 )
add Gpu - Image library
Broken plugin script , closes # 1474 .
updated oscar - aim . jar and joscar with binaries runnable by 1 . 4
Adding some memory settings that any forked surefire tests can utilize
add tools . jar optional dependency
add credentials on the command line
Fixing broken image
Catch badly formed URLs in WebView accessibility injector .
prepare for next development iteration
fix the syntax error in doc tutorial
Fix travis
Remove < application > tag from manifest
Rename drawHelper . java to DrawHelper . java
Fix naming issue in comment
Correct the example maven dependency to include < type > apklib < / type >
Fix indentation
Create README . md
added missing def
Fixed Travis for JDK 7
fixed spacing
missing file
Remove another scheduled - for - deletion class from the preload list .
added Android Arsenal link on Readme file
Add an armv6hf library for Serial
Should explicitly specify source = 1 . 5 .
Used device art generator for screenshot
Add README .
Removed forkMode = never on Persistit tests
Fix ignore list for prevent committing keystore file
wait a bit
Fix typo in docs / index .
Shortened name of target artifact with all dependencies
Fix typo - duplication of SHA - 384
delete generated files
gh - 66 modified mapkeeper readme
remove stray character in POM
Make the README point to the robolectric home page instead of jasmine
adding necessary build libs
switch back to old encog , the new version breaks a test for yet unknown reasons
prepare for next development iteration
Do not show article tab for non - articles
fixed compilation error
Create README . md
disable export of artifact
Switch favicon . ico value
Add Travis secrets for snapshot deployment .
spell your name right yo
add apk file
Fixed checkstyle error
Fix indent
removed testing release from ' all ' task
added wrapper task
enabled proguard
Added one field more to cycle table .
Fix executable permissions left out of commit for HIVE - 1487 .
Now deploy the JAR as well ; bump version to 0 . 6 . 1 .
iOS InAppPurchaseManager plugin should accept all possible transactionStates .
updated test dependencies
add jniLibs . srcDirs
Create License . md
added support for AssertStatement
updated plexus component metadata plugin
I hate double quotes
Add mapreduce - client - core lib .
Forgot to add this
Include strings . h for the strcasecmp prototype .
add method GraphTableCell . getRefsToThisCommit ( )
fixed javadoc
Shutdown of OSoftThread now also interrupts the associated thread
Fixed a bug in skipElementValue ( ) when skipping array values .
Set Android target platform to 21 for NDK
Allow Travis to use JDK8 in the build matrix
moved file to top of repo
quell ant runtime warnings while executing target build - test
Upgraded Gradle from 2 . 2 . 1 to 2 . 7
Remove annoucement on BottomSheetDialog Background
added circle - ci config
Allow categorical encoding .
prepare for next development iteration
Renamed screenshot file .
Fix pom . xml dependency on support - v4
Resizing a demo images
prepare for next development iteration
removed unneeded jsp21 configuration
Rename txtfiereader . md to txtfilereader . md
New build tools
Add h2o src jar .
shutting off external stop messages once again
Add IntelliJ project files and Gradle build directory to gitignore .
Adding maven set version backups to gitignore
Use build tools version 18 . 1 for SeriesGuide modules .
Fix jar building
Fix incorrect Activity declaration .
added sources to junit jar
Git ignore local . properties
Updated splash screen
remove me note
prepare for next development iteration
LPS - 26650 rollback icon , will add it using ant
added ISchemableSpout interface
Sample data
setting sources version 0 . 9 . 11 - SNAPSHOT
added missing version
Add headers in english version
fix another bug that prevented the gl debugger to work
Working a bit on the test to see what ' s going on with Jenkins .
Add example dataSourceFactory properties to reference . yml
bump version no .
Added getter to the user object associated with a base adapter helper
do not dramatize queue overflow events
Add files via upload
Add jcenter to global repositories .
Corrected a tiny comment typo .
add screen
gluegen - rt 64 - bit native has a proper dependency to mscvr80 . dll now .
implement LLAP UI as a separate service - part 1 ( binary patch , addendum )
Fixed typo .
edit NEWS
add gif file
adding the latest contributors
Add format - headers .
remove jdk requirement in deb packaing .
Add a header description
Create README . md
rename a property to better reflect reality ( missed one instance in manual fixup of merge conflict )
require GWT 2 . 2 . 0 for its java . math support and testing improvements
Added SortedHashMapTest to pom . xml
prepare for next development iteration
Create README
Moved resources to src
Added README
add circle ci node cache
changing name of the lib
add todo
remove unused import
added chromecast to changelog
Upgrade job . query to be medium text
Add retina version for executeMavenGoal . png icon .
Freshen screen shots in help screens
Fix NullPointerException
removed test rule from demo
fixed fragements back stack problem
added test for bug # 2527998
Remove oracle . sql dependency also from OSGi information in pom . xml
Updated gradle plugin to 2 . 1 . 2 .
add xml deny functions
removed test files
added changelog
Fix sample code
apply osgi gradle plugin so the we can use javanica in a OSGi Enviroment
Add files via upload
ACT - 1366 Added image for userguide
Updated gradle version
Enforce 1 . 7 compatibility in the plugin .
LPS - 34599 Update the DTD , because it ' s documentation for non IDE developers
fixing up a couple more 9 patch images
update min sdk support to 9 , fix async execute not call doInBackground when api version > 9
added type name .
Fix typo
Remove blank line
update worpress - gradle plugin to 1 . 1 . 1 - supports debug build with local dependencies and release build with artifact dependencies
Added nil check to RCTModuleData
Updated classpaths to match default Eclipse import ( jnalib ) .
FastArray doesn ' t overwrite toString ( ) method
Renamed README . md in res folder to .
Fixed eclipse import for migration
Delete pickerdemo . gif
Bump version of maven - dependency - plugin .
remove unused build step
Reflect current implementation in spec .
Drop the minimum required version of maven
updated name in readme
build apidoc during package , not during install
remove no longer used ' pdex ' directory
Updating source compile android . jar library to rev19 .
fixed timestamp extractor documentation Java example
Create README . md
fix test data
LPS - 65336 create class in package with suffix control / menu
disable ci
Fix gzip streams buffering data for low volume streams
remove unnecessary output
Ignore journal directory in git .
Adds a .
Modify gitignore
don ' t do anything else if - - pluginlist is specified
LPS - 39137 Fix bad SF compile error
Added README
Adding travis configuration
Updated Gradle plugin .
update the examples
do not ignore gradle - wrapper .
Use new Travis CI container infrastructure
Add files via upload
hide no - tabs toolwindow on middle - click on base label
LPS - 67352 Set tab width
Do not limit the client ' s heap space ( See FLINK - 934 )
Fix bug when adding months
added buildSrc to the gitIgnore
Add debug keystore
Added files via upload
Remove empty destroy ( ) method from GLColorOverlay
Fix typo
removed staging repo
Add ' flashbuilder ' plugin to clients / flash / build .
Add Copyright in License file
Updated gradle plugin to 2 . 2 . 0 .
Add local . properties to gitignore
correctly sized dmg background
Fix sample code for any orientation .
add module to parent pom definition
Updating the timeout due to known travis issues
Disable ValidFragment lint check .
Stopped eclipse plugin download java docs
replace nimbus . host with nimbus . seeds
update travis config
added documentation image
Fix builds
Remove unnecessary .
But this time try it without broken links .
Fix javadoc plugin errors
Add shared library extensions from other platforms to .
Removed unnecessary annotation
added snap video
Unified the " .
Added missing image .
set correct version
Fixed typo
Remove unused import
enable git VCS at idea via gradle
Remove tehuit from lib as it is auto generated
added javadoc task
bind manager web ui to 192 . 168 . 49 . 1 as well
Created config file for travis CI
Add wrapper for travis
Set the " release " SigningConfig to betagroup ReleaseType
Updated h2oEnsemble README
Fix Issue # 562
Fix use of SkMutex .
Rename sr - rRs to sr
make gradlew executable
add exuberant ctags dependency to travis
doxia - module - markdown 1 . 5 supports page titles
Fix a failing test input file
remove extraneous endif
Add main / dependency - reduced - pom .
Added redundant abstract method declarations to maybe work around problems on Nokias
Add sample APK
Fix param for Metrics Consumers
raised minSdkVersion
updated CHANGES
Adds Travis CI
Fix NSInvalidArgumentException
fixed image size for styling
need h2o for runtime python version recognition
Create release - notes .
add de translation files for map creator
add docker import
add travis ci config file
Removed unused import
took out jdk6 from the travis build
add triggers README
Add back derby settings as running in IDE without maven and properties set
Fixed typo
setting example schema version to 1000
Add dependency
Fix typo
Keep string pool until after strcpy
add a future todo item about including URLs
specified number_of_shards 5 to make sure the two docs end up in different shards that can be refreshed separately
Test travis CI .
update support v13
Updated changedlog
Create README . md
Fixed Travis configuration
add Gson library
Remove @ ToBeFixed from knowntags .
reset CodeInsightTestFixture in tearDown
update version to 1 . 0 . 0 .
don ' t sanitize pipeline group name in getGroup
shutting down the listener thread properly { SMACK - 120 }
Report the version of java found by zap . sh
ignore disconf - web for build
Enable Checkstyle for tests
define height for context images to avoid content jumps on load
Throw UnsupportedOperationException in not implemented method
Remove " allowBackup " from this file
improve speed of message detail action
Fix a bug for users with space in home path .
Ignoring kannotator in testData .
Updated wrapper jar , so that the installation via Gradle Wrapper is multi process safe .
fixing iso - build
Put h2o - package output file in .
add notifications for irc
Fixed small comments
Remove comma
prepare for next development iteration
Restore default code sign to avoid error on iOS 9 . 2
Upgrading AWS SDK
Added comment describing JDT bug workaround .
update screenshot
Make script non - executable
Bump gradle wrapper to 1 . 10
Add shippable config
Remove unused import .
fixing relative path of android module
gh - 31 - Removed integration tests from travis
fixed compilation error for ' Html ' class usage .
Add gmetric4j library .
Removed junit from classpath ( all tests moved to zaproxy - test )
Detect broken connection via SQLException
Added testing modules to jooq - parent
Added empty settings . gradle so that Gradle does not search for it in parent dirs .
Fixed title of web page from KairosDB 2 to KairosDB .
Fixing Mac installer ( OF - 431 )
Fix XML end tag .
Add case insensitive command .
Add rootProject name
Revert sourceSets modification . . .
Add app / views / build directory
Fix relativePath property for application pom
remove redundant brace in build . gradle
Fix build
Ignoring further changes to gradle . properties
Prepare next development version .
shrink screenshot
Update android build tools
add yui - compressor to tools /
relocate gluster mount point to / tmp to allow non - root to create a local fs cluster
Use an empty .
add javadoc link to JDK 5 apis
add releaseBackup to ignore
add external link to test page
reverting release . scope = patch
do not ant . info ( ) stage message if state printer is assigned
Moved two NOPASS tests to pass .
Updated the 3 . 2 release notes
Switch jcenter / mavencentral order
Ignore project files of Eclipse and Intellij Idea IDEs
Renamed NN sample
delete origin
Fix deprecation warning .
Exclude stress / thrift from jacoco
update sample gradle setting
Ignore Rsandbox directories .
HHH - 5294 declare source files encoding to utf - 8 to avoid maven warning
Remove minidns dir
CODENVY - 338 Remove explicit guice dependency version ( # 1556 )
remove svg interpreter
adding aapt for Build Management
Write checkstyle to stdout .
Add missing websocket dependency
Fixed typo .
Rename tool scripts
Fix build , previous commit failed to remove an import
Add email notification address
Adding - daemon option to zookeeper - server - start .
Remove unnecessary dependency in build . gradle ( # 4086 )
Added executable flag for subversion as well .
Temporarily disable intermittent tests on the Maven grid
removed unused method
Updated Android support library , mainly to fix crash in Android 3 . x devices due to new API for notifications
Updated docs
Upgrade Ivy 2 . 2 . 0 RC to final
Only show public members in Javadoc .
Fix build
Fix repository language statistics by adjusting .
see CHANGELOG . md
Add exec permission to gradle wrapper for travis
Deleted some generated files
added workaround for broken openjdk7 on travis
update android gradle plugin to 1 . 0 . 1
Added sqllogic . log to .
Updated CHANGES . txt
Added tools . jar to classpath for buildSrc
LPS - 56976 CounterTransactionExecutor does not need the BaseTransactionExecutor , just directly implements TransactionExecutor
Remove extra line at end of document that was accidentally added
ToString usage example had a typo in it ( used ' excludes ' instead of the correct ' exclude ' ) .
Added bat - file to push to buxs . org - repository .
Add ANTLR 4 reference repository as a submodule
Fixed ART background color
Use new oss - parent 9
add test / integration folder to fix bbb - client
add okio dependence to keep it up to date
update icons
update FileRequest
Fix testdata
Add first travis config file
Maven web project should name the war " source . war "
Ignore Eclipse files .
Label Adjust description .
Removed unused file
Removed folder config
Updated release - proguard . txt to fix # 159
fix pylint build file ( # 1005 )
capitalize first letter of the folder name
Add build . properties for the open - source project .
added other implementations
Add 9 . 1 release date .
update readme for new usage
Delete version
Removed old junit jar
Remove dangling reference to bazel - tools
Delete unused background .
added Sams name ( damn I got distracted , meant to do this some time ago )
Write checkstyle to stdout .
update travis . yml
Add description
not used any more
Fix Hierarchy addon presence .
add @ Deprecated to make sure it is not part of 1 . 0 . 0 API
Setting project version as well from the prepareRelease task , although this isn ' t currently used .
add ' elasticsearch ' comment to indexer . yml
enable travis
Set createDefaultUsers to true ( for now ) .
Remove executable flag from bootstrap config .
Fix automerge issue
LRQA - 29060 Never set result to NULL
add travis - ci support
Added a TODO
Added gradle . properties to resolve # 8
prepare for next development iteration
Added GL_PATCHES as new constant
Fixed pom . xml making a ' true ' file .
Fixing Mac installer ( OF - 431 ) Not only for installing , but also upgrading .
Removed duplicated library
Add fullBackupContent to Sample Android Manifest
Run the spock - specs tests in parallel .
Remove SNAPSHOT to push to maven
Fix NPE in style fragment parse
Disable unique snapshot versions
Moved gradle to 1 . 10 and gradle - plugin 0 . 8
updated version
Set default icon size to 24dp
Remove redundant call to ` setBuildFile `
Missing tld .
Added File
added Matthias and Josh to the travis CI email notification list .
Add util and .
Set classpath scope for exec - maven - plugin to " compile "
uploaded v1 . 0 . 2
Add gitCommit to version resource
planTextBytes = > plainTextBytes
Build tools 19 . 1 . 0
update druid
Missed import
list of flow test to ignore for phantomjs smoke test
build . gralde add libs dirs
Upgrade xerces dependency for cxf ( QA failing due to Xml parser changes of yesterday )
Restore credits removed by r1003846
Replace Derby by H2 in data / README .
Remove code highlighted as unused by UCDetector
updated PDF
Don ' t actually fail build on clirr error
Do not use xhdpi app icon with beta label
add log4j jar
updating changelog
build gradle
cleaning up dist
Bumped docs version
Change groupId to com . fivehundredpx
Adding IntelliJ ' s ' out ' directory to .
LRQA - 26245 Add test property for running functional test on Firefox 45
Add dummy deepwater interface jar ( 7kb ) .
maven central requires fixed version
Remove zip file .
removed dependency for slf4j - simple
Added package . html file for the solo package .
Reduced header size
Define the minSdkVersion variable
removed override .
applying Romain ' s fixes for growl
Add a gradle task testsOnJVM .
added gitignore
Upgrading to ant 1 . 5 . 4
Point the correct property of the compile sdk version in the gradle . properties file
added screenshots
update gif
Fixing Travis
added factory method class diagram
added file mode back
Add compile . debug flag .
Adds ES_INCLUDE on rpm
add demo res
removing comment about iterator
Removed useless variables .
Add performance tests for add , addAll
using java5 compatible version of guava
Remove index . html
Upgrade maven - compiler - plugin to 3 . 0
remove redundant resource for notify icon
improve supersu compatibility
Adding build status lable to README ( # 146 )
Adding a file to learn
Added explicit version to Scala plugin
Log full stacktraces of failed unit tests
add xstream dependency
removed a file generated during test
Remove hardocded previous version
Add ServiceLoader file for tachyon KeyValueMaster
removed extraneous import
Fixed added whitespace in AbstractAtomicReferenceOperation .
remove dead otr4j submodule reference
updated contributors with more details
LRDOCS - 527 Remove unused argument
Remove old stuff from .
Remove redundant unit in zero value form CSS .
removing cinst
print a message before fetching available versions
remove unused sources and broken link to sources in library
Revert test .
Only execute the builds on slaves with the android label ( # 3230 )
add gitignore intellij files
Add missing test mannifest
Remove failing pro guard configuration from performance example
Add the command to install libtool for Mac OS X developers ( # 1009 )
Updated submodule
disable appcache because it causes some charset issues with russian locale
remove owners and groups file
build target android - 17
Prepare next development iteration
Remove local testing file
test travis build
Fixing transitive - ness of provided
Use the u2020 blue for the telescope icons
flex plugin imported fix ( IDEADEV - 38016 )
removed extraneous orientation attribute
Tuned the README . txt and LICENSE . txt files .
Removed old files
Bumped version
We don ' t need an application element in the library
added seekbar . png
remove second occurrence to avoid future issues
Bump version number to 1 . 1 . 5 for Maven
Rename licence . txt to LICENSE
remove an unused import
Initialize country and dialect specific engines .
Updated version number
add package . json for node
add clhm - production .
Add funnel image in DesktopAppearance
Create README . md
Add missing density - specific resources
Fix type in TwitterRestClient .
Fix typo
Fix comment
Adds shebang
ignore * .
Fixed formatting / printing bug in CXDChunk .
Fix formatting so - - docker option doesn ' t get obscured .
prepare release checkstyle - 7 . 3
Remove protobuf 2 . 2 . 0
Remove redundant ` private ` modifier from enum ctor
Added screenshot .
Remove obsolete file
Fix check in dialog progress indicator height .
Made the header image darker
Setting default name for multi - project
Remove invalid import .
do something useful
Corrected association declaration .
Set version to 3 . 3 . 0 from 3 . 3 . 0a
use UNSPECIFIED github token to build locally
make translator name clickable
fixed # 268
Remove unnecessary " to " from docs for libraries
Add screenshot
Add # !
Upgrade ActionBarSherlock to 4 . 2 . 0
disable travis cache
Testing svn version info
removed unnecessary import
Disabling all version removal for test
Add missing @ Override annotation .
remove old submodule
missing AgentQuitFromTouchingBlockType lava had broken tabular Q learning sample .
removed unnecessary import
Fixed error in devkit pom
Remove duplicate streets
add waffle . io badge
Renamed package
gh - 24 - Added basic travis config file
add png
add 1 . 0 . 4 section
fixing typo
Remove vi ' s swp file
adding extra - android - m2repository component
Remove unneeded icon .
bump master to 3 . 0 . 0 - SNAPSHOT
Adds water normal maps .
Updated cucumber - features
Set correct permissions on the script .
commented out a failing line
prepare release HikariCP - 1 . 3 . 8
add release notes
Add AbstractProcessingFilter . getAuthenticationDetailsSource ( ) .
removed extraneous JAR
add intellij files into gitignore
Removed Roboto fonts from assets .
fix missing processFormFields
missed one file
LPS - 51081 Remove parallel clean for now , to avoid race conditions on some machines
Adding the .
Add color picker library
Removed documentation static from repo
Upgrade Apache Commons Collections to v3 . 2 . 2
Fixed typo .
updated library version
Added checkstyle , classpath , project , and settings to gitignore
We should not be having a compiled version of cordova . jar in the test directory
I have separated the ` show ( ) ` from initialization , it is more extension malleability .
Rename LISCENSE to LICENSE . txt
Translate few missing resources to French .
add readme - cn .
Delete lib / super - csv - 2 . 1 . 0 .
Bump README to 1 . 2 . 1
set dev
ignore rules for files generated by zeppelin - examples
update travis conf
Added test for " 005 " value in xml attr .
Replaced Beep . ogg with a better one
missing colon
speed up test coverage check
ignoring * .
Fix build version for split - out artifacts
bump up 1 . 1 . 0
disable tqdm monitor thread which leaked
Added files via upload
added icon
exclude test - * .
added travis CI file
update gradle
Remove unused boolean parameter
Updating examples
updated version
DialogManager - > MainWindowUtil ; added setTitle method
remove unused constant
removed shear functions
updated version
Add artwork
Document need for more test coverage
Add Droid Ethiopic fonts
added CHANGES file , every contributor should add a quick note on what she changed if it breaks the API or adds a new API
Ignore eclipse workspace files
update demo
handle execptions while writting to the debug stream .
include sys / ictrl .
changed a typo from SHNAPSHOT to SNAPSHOT = )
activating travis test script
add missing font file
Also update the build - tools in travis configuration
add readme for sample app
Added distribution jar .
Add use for audio_unique_id_t
Added circle . yml for CircleCI
prepare release HdrHistogram - 1 . 0 . 8
Changed name of Authentication example templates to be consistent with
Add caching for m2 folder
updated version
add more to CoordinatorService
Remove unused class
remove useless file
renamed bin scripts
update gradle wrapper to using gradle 2 . 2 . 1
update sample . apk
Remove target from .
Add support for building and running our tests with Gradle
rc is missing dataset
removed - i option from travis configuration
Fix memory leak
Updated CHANGES . txt
Delete line
add missing invoker . properties
add cardview dependency to the main lib
gh - 131 - REST remove file
reapply fabric puglin
Ignore local changes on .
