update changelog for 1 . 1 . 1
Added missing JNA jar
Adds lintOptions to Library .
Add missing JSON highlighting to example .
correct a typo in a comment
Added missing images
Restored @ since javadoc tag of Convertible
Added idea project files to git ignored files
remove fiel
prepare for next development iteration
do not use the lastest tool on travis
Change xml tags order .
still need a res dir to prevent eclipse from freaking out
Disable clip to padding for row items to avoid clipped transition animation
Ignore tests in release perform as they ' re already run in the prepare stage
Add maven central repo to readme
remove mail notifications ( for now ) from travis
Only run findbugs for main
Fix build issues
Add CHANGELOG . md
upload demo gifs
Updating parent pom version of reporting to 1 . 3 . 0
Add screenshots
Created tech - debt entries for all components and laboratory components .
add ignore for jre . tgz on linux
Fixed method layout in ActivityApp
Turn off baseline aligment in wide show info layout .
prepare release checkstyle - 7 . 1 . 2
added few known transitive verbs .
Skip deployment of integration - tests
Require Maven 3 . 0 .
keep deprecated requestFBOLayer ( ) method for now .
remove old
Appease the checkstyle overlords .
Fix ` maven_repositories ` section link
testing out travis as ci
added Travis CI configuration .
Add shell script for zan
Remove fflush from hdr_percentile_print .
update parent pom
Increment gradle build tools
Create README . md
Eradicate whitelisting
Updated gradle release plugin dependency to 0 . 1
Bump pegasus version to 1 . 8 . 5
corrects tests for GROOVY - 2774
Removed unnecessary asset
add execution permission to " input " script
Setting default name for multi - project
LPS - 22149 - This will lockup the browser
Updated dependency version to latest release
Fix build .
gh - 471 - updated travis script
updated CHANGES
Don ' t build aggregated source jar .
added info option to travis to output more information
Add Eclipse files to .
rename unit - tests execution to default - test
Removed Key Value Server from SVN repository .
Add Application class .
Delete android - support - v4 .
Reorder modules in top - level pom . xml
Added gitignore .
update demo
added checkstyle file info
add jdk
Fix crash bug when click capture button after set a filter
add gitignore
remove old screenshots they are not representativ anymore
Removing unused imports .
Ignore IDEA directory
regenerate gradle - wrapper . jar using 1 . 10
typo , removed sys accidently a couple days back
regenerate gradle - wrapper . jar with 1 . 9 - rc - 4
Adding execution permission to the shell script files
Adding bin related files to gitignore ( # 130 )
Changed version
Reseting a project . properties file
Get me out the stupid readme file .
Reduce the amount of logging from the Javadoc plugin .
Fix typo which cause stack overflow if children ( ) was called
Added reference to distribution .
Create grade files to appease NetBeans plugin
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Fix build errors with m2e
Move the pyunit_DEPRECATED_random_attack_medium . py to pyunit_DEPRECATED_NOPASS_random_attack_medium . py .
create docs directory
Make privacy provider single user for multi - user environments
removing stuff useless for release
Add org . jetbrains . android as dependency
adding IDE related files to .
remove mongo . jar and bson . jar on clean .
Added files via upload
Move QueueFile to ' io ' package .
rename code style jar
added favicon
Created PopularMoviesView
change the default release scope to be patch
Ignore project configuration files for NetBeans
prepare release storm - hbase - 0 . 1 . 2
run tests in build
Permit the folder list item to expand vertically .
Upgraded maven - release - plugin to version 2 . 1 .
update build tools and target api
use the passed param for ' rand_shuffle ' when writing flatfile ( I had left it harwired to True .
Ignore Eclipse project files .
removed erroneous tab character
Created tech - debt entries for all components and laboratory components .
bump version for 0 . 9 . 0 release
update doc
Fix markdown rendering of bullets on homepage
Remove unused import
Add tag required by schema to Cobertura configuration .
Changed version number
fix build for example project
Set minSdkVersion to 8 for DroidGap project
Removes extra padding introduced during merge from develop
Remove unnecessary permission from gallery app
Remove ignored file
Create README . md
die extra plugins
Fix mistype
Add icon for the project
Adding a ' .
Add a README section for open items to remind me to check & test XML
Skip javadoc
Add steam output to .
Test travis CI .
do not show gpx export items at start
prepare for next development iteration
Renamed test process to make the test run on case sensitive operating systems
Add test - reports / to gitignore
adding jna for native library access
Only CI build the master branch
Ignore my TODO list
Added package custom
moving logo to wiki
Permit the folder list item to expand vertically .
Removed some unnecessory code
Add icon for the project
add icon
Fix broken build
Have a bottom actionbar in the Search activity to be consistent .
Skip the enforcer plugin in the examples
Fix a rare NPE crash in Android 2 .
Added support for automatic legend generation for Wheelchair renderer
upload demo gifs
Test can take more than 10 minutes , use travis_wait command to allow them take up to 20 minutes .
Make gradle wrappers executable
Create README - ZH .
Added check for invalid scope
Inflate my ego ( add Aphoh to the contributors list in README . md
Removed unused resurce
remove unused logger
forgot this guy
added the Gremreaper logo .
Add intellj project files to .
remove warning
added idea ignore config
Added files via upload
Removed Merriweather light variation assets ( since they won ' t be used )
Updated screenshot
Added high res launcher icons for xhdpi and xxhdpi .
Delete default README
Removed javadoc dependency from javadocJar method to avoid automatic javadoc build
added getNotificationUri to comply with API level 19
Remove redundant openjdk7 , non - existing openjdk8 from Travis - CI config
Guarding moved pass CheckRegExp with skipNonTranspilationPasses flag .
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
update travis . yml
change wl12xx hotspot ssid to spike
prepare for next development iteration
Fix checkboxes for message_list_item_touchable .
Removed DoubleCheckedLocking from checkstyle . xml .
Add maven central repo to readme
bumped min maven version to 3 . 2 . 1
Remove unused import
Ignore project configuration files for NetBeans
Add slack integration for travis
rename file so its title has a space in it
remove deprecated @ S3method roxygen2 completion
Prepare next release
add execution permission to " input " script
Add support library , to be used for ViewPagers
Add CodeNarc rule exclusion
delete junk
Add xxxhdpi drawables
Set isInEditMode ( ) to true # 9
bumped version
set IDEA JDK from build script
Fixed invalid jdk range in pom
Use Travis - CI ' s container based infra
update travis
Delete default README
prepare release HikariCP - 1 . 3 . 5
Adding binary folder and .
Fixed case of SideBitFlag
Setting build group and version
Created tech - debt entries for all components and laboratory components .
Add Eclipse files to .
Added person .
Should fix black laser beams .
Update build tools to 21 . 0 . 2 .
Fix extra right bracket
Removed old symbol pattern .
Updated build tools and sdk
Add Eclipse ' s bin / folder to .
LRDOCS - 2232 Remove unneeded property
Revert travis change as they do not support java6 anymore
LPS - 30589 Added / bookmarks / find_entry to auth . public . paths
Build ' client ' target with - Wno - sign - compare .
update changelog for 1 . 1 . 1
updated example yml keyStorePath - > keyStore per the new config
turn off active by default on tests
Only build tagged versions
Fix Test
preparing release version
rename main file
Remove the over quoting .
remove PIDFILE at stop time
adds awesome image courtesy of the internet
upToDateWhen = false
Specify version name for subproject properties
Create README . md
Update build branches
build make buildlog include tests run and fail stacktraces
Added Example apk
Add forgotten static file robots . txt
Add config for TravisCI
Add BAD_PACKAGE_PROPERTY_ACCESS DiagnosticType to the VISIBILITY DiagnosticGroup ( which transitively adds it to ACCESS_CONTROLS ) .
Add Travis configuration .
ignore class files in root ( which are generated by " gradle test " )
ignore examples directory for rat
bumped version
Fix the - - dev_mode flag .
Upgrade Anonymous Usage Statistics to version 1 . 1 . 1
Expose NETWORK_SCORE_SERVICE as @ SystemApi .
Adding mavenLocal ( ) for local resolution
fixed test
fixed git ignore name
Fix NPE in PackageParser
Fix config
added 1 . 8 . 1 hotfix
config not needed aynymore
added phonegap icon to demo2
update Alipay and Weixin
Changed version number so I could push the new version to dist .
Upgrade JUnit to 4 . 12
Create README . md
Delete default README
comment out snapshot plugin for release
Create PULL_REQUEST_TEMPLATE .
Add maven central repo to readme
Add CLA documents
Added tag 0 . 1 for changeset d04a8ef4ccb0
Remove Gradle wrapper files from .
Removed lib / .
Log stack traces of test failures to the console .
Added missing property for playWhenInactive .
Remove unused file .
Add microbench to the module list
Updated gradle release plugin dependency to 0 . 1
Create README . md
Adding execution permission to the shell script files
add gitkeep for assets
add intellij * .
Set travis jdk to java8
Added OGNL expression object graph expression language jar
rename code style jar
added missing imports
missing curly brace in ip_range aggregation example
add execution permission to " input " script
Add missing Override decorator
Fix name of java executable
updated jsr166e to the 9 . 08 . 2015 version
fixed an error in the pom . xml file
Make log4j an optional dependency
bump version for move to Apache incubator
Delete demo_shifting .
In onKeyUp for DPAD_CENTER , show the IME for text input .
prepare release HikariCP - 1 . 1 . 6
Fix data driven testing example in documentation
Use Travis - CI ' s container based infra
don ' t set the application title in the library
Move file to correct dir
Set isInEditMode ( ) to true # 9
Bump readme version
Removed unnecessary return statement
Create README . md
added missing def
Run the tests on oraclejdk7 and openjdk6 + 7
missing return in svg ' s getCoords
Added screenshot
LPS - 65607 Export the concrete package .
removed unused image
upload demo gifs
Compile tests with source attribute .
Add service graphs
Created tech - debt entries for all components and laboratory components .
Exclude JMH tests from coverage reports .
Add text editor temporary files to .
remove debug output
Fix markdown rendering of bullets on homepage
Renamed maven assembly to jmxtrans - all . jar .
Recommend jcenter repo .
Removed the .
Add extension to README file .
Upgraded slf4j - api from 1 . 6 . 1 to 1 . 7 . 2
Added dash to test push
Add CLA documents
Updated jol to 0 . 2 to resolve the slow startup problem due to heavy GC
prepare release storm - hbase - 0 . 1 . 2
implement missing method getGlobalPosition
fixed NPE in Box . extendToEncompass , close # 1783
Create README . md
Reordering the build repositories in the hope that this fixes the jenkins build .
update favicon
Add credentials for CI snapshot deployments .
fixed license
added wiki images
Properly stop server .
Remove unnecessary code
Add a new ' pre - checkin ' target to help keep checkins clean .
Bumped wrapper version in the build file for consistency .
added OnionKit library import
Removed @ Override annotation
add execution permission to " input " script
Setting build group and version
Ignore OSX and IDE files
updated changelog for 0 . 9 . 5
Added intelliJ hidden files to gitignore
Add Readme file
added support for AssertStatement
bump version for nondex - maven - plugin to 1 . 1 . 1 ( # 3439 )
Use the latest version of Android Tools
Added missing JNA jar
Added files via upload
set IDEA JDK from build script
add getCount method to BytesInputStream ( @ MysteryMachine )
added TODO
add an accessor for the executor service
added few known transitive verbs .
Raise toolchain version
Remove jre6 support .
fixed git ignore name
Compile tests with source attribute .
Set gradle version to 2 . 2 . 1 for compatibility with Nebula NetflixOSS
FredrichO - fixed spacing on the bottom of the number of columns in the media gallery settings layout .
Create circle . yml
Added ignored_columns .
prepare release curator - x - zkclient - bridge - 3 . 0 . 0
Add smaller sized screenshots
Remove provided scope of support lib dependency in pom . xml .
Change the size of the gifs .
prepare release checkstyle - 6 . 16 . 1
build make buildlog include tests run and fail stacktraces
rename for letter case
update version of build tools
added gitignore .
Set daemon flag on poller threads .
added idea ignore config
Exclude pom generated by shade plugin from list of modified files ( minor )
Updated build tools from OC JB workaround app
changed dataset .
Remove the launcher filter from the AndroidManifest as per # 57
Corrected junit jar
Ignore gradle related files .
updated splash
add getCount method to BytesInputStream ( @ MysteryMachine )
prepare release storm - hbase - 0 . 1 . 2
Remove unused file
added ISchemableSpout interface
Add local . properties to .
Upgrade to Reflections 0 . 9 . 9 - RC2
Remove inspektr dependency version number since it ' s defined in parent POM .
Added reference to distribution .
Add KHR_gl_texture_2D_image extension string .
fixed compilation error
Deploy snapshots of 1 . 1 branch with Travis CI
Release the version 1 . 3 . 0
Implemented getOpacity
set IDEA JDK from build script
Add files via upload
Remove nasty mavenLocal ( ) from repositories .
Log stack traces of test failures to the console .
Added files via upload
Fix build .
add resource dir for tests
Removed new lines
add 1 . 8 changelogs
Added 2 . 4 . 5 release jar
Add pbethe @ to bazel CONTRIBUTORS .
initial git ignore file
added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
Ignored Eclipse files
Sample gif
Add logging of Bintray user for CI
updated jsr166e to the 9 . 08 . 2015 version
included default .
prepare release HdrHistogram - 1 . 0 . 7
Create README . md
Rename LICENSE to LICENSE - 2 . 0 .
Adding top level .
Remove post tag in circle file to attempt build fix
Add ABS as dependency to library ( fix # 559 )
use underlying type for builtins
Remove unused import in BufferUtils
update changelog for 1 . 1 . 1
Changed field type of username in jiveGroupUser .
added wiki images
Freshen screen shots in help screens
Fix indentation and code style
added few known transitive verbs .
Set default attachment preview image in the code ( and not only in layout ) so that whne moving from a message to another we get the right preview
Add changelog to track high level changes of each release
Remove unnessary bundle package
update com . android . tools . build to 0 . 4 .
Added Commander / SourceSafe to the list of checked plugins
Removing accidentally added file
Create README . md
Incremented the version code of the sample project for GPlay upload .
add the mavencentral repository on the root level
Add demo gif
Add depart icon in itinerary step row
Use Gradle Android 0 . 6 .
Set source and target compatibility to Java 1 . 7 .
add eclipse and idea projects to gitignore
Updated icons to better comply with Android Developer Guidelines .
Changed build tools version to 23 . 0 . 3 , don ' t use rc version
Allow null string input
Add a recent change
Fixed test for changes to ' model ' report output .
updated gradle build tools version
set IDEA JDK from build script
Create img
FastArray doesn ' t overwrite toString ( ) method
Give proper extension for markdown .
Fix style on build . gradle
Delete a . gif
Upgraded maven - release - plugin to version 2 . 1 .
Include a call to ` ulimit - a ` when building in Travis CI
Removes the TODO to upload the library to bintray / jcenter
Change maven prerequisite to 3 . 0 . 4 to match the maven api version
Fix formatting
updated sign stage
Updated changelog for 5 . 5 . 3 .
update android natives
Add CHANGELOG . md
Create README . md
Fix testdata
Move H2OApp into a package
fixed file name of travis script
added checkstyle file info
remove debug output
ignore swp files
Git hygiene
Ignoring build - data .
Added gitignore .
Fix checkstyle
Ignore bin and gen
add travis - ci config
update to latest gradle plugin
Fix # 183 - update screenshots
add apk demo
Testing Travis Container Environment
Added screenshots
do not leak menu - > root_panel - > .
Removed DoubleCheckedLocking from checkstyle . xml .
apply proper quoting to crash arguments
Modify changelog
add jekyll _site directory to .
add Sample Apk file
add progress cycle
Call AudioTrack . flush ( ) before AudioTrack . release ( ) .
Prevent infinite loop on exception
Reordering the build repositories in the hope that this fixes the jenkins build .
Add eclipse plugin .
Corrected license identifying information .
update com . android . tools . build to 0 . 4 .
added war / to gitignore of template
Resized header
Add missing curly brace in the README
HHH - 3580 added entity manager to module list
Reinstate view example for screenshot tests
Ignore lint warnings for unregistered activities
Reduce the amount of logging from the Javadoc plugin .
Ignore OSX and IDE files
update travis config
add the snapshot of demo project
Hebrew uses language code iw apparently .
die extra plugins
bumped version
Upgrade maven - javadoc - plugin to its latest version 2 . 9 . 1
remove unused resources
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
Add art assets
Fix mixed line ending characters in .
Adding image folder for Flow documentation graphics
raise version
Fixed typo
Removed unused import .
Add vcs root
Not using any more
Create Jar artifact with test code
add Question 4 . 9
Add travis config
Adding missing gradle library .
Fix signing fallback .
Added screenshot
Fixed case of SideBitFlag
Add a LOG_TAG for android . graphics . Graphics JNI .
corrected pt_BR directory name
add execution permission to " input " script
added travis - ci config
bump jsonassert
bump socket . io for tests
Fix resources
Ignore gradle related files .
Remove extraneous semicolon .
Updated sample for release 0 . 6 . 1
Fix param for Metrics Consumers
Bumped minSdkVersion
update CHANGES
Added auto unit testing
Fixed p . filter param
added wiki images
add in missing module traceback
Add change log .
Create webapp / llap directory for MiniLlapCluster
Log test errors .
Add Travis - CI YAML file - # 722
Remove unused import
drop jdk6 from build matrix , we require java 7
jetty - 9 commit test
Ignore temporary generated site .
Get me out the stupid readme file .
Adds lintOptions to Library .
Fixed deprecation
Fix stupid copy / paste typo .
Updated build . gradle for maven
add 1 . 8 changelogs
Fix REST test delete / 42_missing_parent to catch a RoutingMissingException
removing unnecessary support extra for Travis
Updated support library
fixed typo in changelog
add README
Fix Travis
Added missing jars from DirBuster integration
Fix data driven testing example in documentation
Remove test I opted to host elsewhere
Bump gRPC to version 0 . 9 . 0
Fixed isUserConfigured
Ignore OSX and IDE files
remove PIDFILE at stop time
remove web
Write checkstyle to stdout .
Fix data driven testing example in documentation
set version
don ' t set the application title in the library
fix dashboard # NO_ISSUE
Remove the over quoting .
Updated gitignore to ignore hprof files
regenerate gradle - wrapper . jar with 1 . 9 - rc - 4
Make hadoop directory .
ignore class files in root ( which are generated by " gradle test " )
rip off jruby ' s travis notification settings
engines are standalone blocks
Updated copyright date in LICENSE .
prepare release astyanax - 0 . 8 . 10 - SNAPSHOT
remove specify developer team
updated pac4j version to the released 1 . 8 . 2
exclude builds for simulator .
update screenshot
add execution permission to " input " script
updated gradle wrapper to 1 . 10
Added support for travis - ci
Remove unused imports
Renaming pom artifact - id , so that gocd shows up instead of main ; when opening up multiple projects in idea .
Only run compile / unit tests in Travis
Fix warning
Added missing jars from DirBuster integration
Removes lib / from top level
Add maven central repo to readme
Add scala back
Bring the children into the project .
Commented the missing function viewUpdate ( ) and added a navigator . notification . alert ( " Ready " ) ;
Add Small ignore files
Changed Spout maven repo to more stable url
Changed field type of username in jiveGroupUser .
Fixed typo in settings . xml
Disable break on lint error .
Created tech - debt entries for all components and laboratory components .
Changed components to use parent pom v 4 , producing source and javadoc jar packages .
bumped version code again
Fix bitmap tinting
Add local . properties to gitignore
Prepare next development version .
resize screenshot .
Change build tools to 22 . 0 . 1 for Travis CI
Adding 2 . 4 . 7 jar
Disable JS tests when enabling the profile dbTests
add gitkeep for assets
comment out snapshot plugin for release
Add robolectric cache to gitignore
Add package . html .
update build . gradle
set IDEA JDK from build script
seem to pass now in the mr - 0xb1 jenkins ( NOPASS_TO_PASS ) tests
Prepare change log .
revert version
Add Eclipse specific project files to ignore .
Move H2OApp into a package
moving logo to wiki
add eclipse and idea projects to gitignore
Include generated grammars in source zip for debugging purposes
update support version to one in travis ci
Ignore target directories
Skip tests for a while
remove bin directory
Upgrade jsr305 2 . 0 . 3 to 3 . 0 . 0
Removed Key Value Server from SVN repository .
Added Example apk
Write checkstyle to stdout .
remove dependency on react - native which will break the packager
Removed new lines
Rename setup_environment to install_frodo .
Fix build
use oracle ' s official jdk
add usage
ignore javadoc build error , correct javadoc later .
add execution permission to " input " script
Exclude gwt files , so that maven tests can run
Remove blank line
updated library
Updated docs
Upgrade Ivy 2 . 2 . 0 RC to final
ensure utf8 encoding of javadoc
add MavenCentrail ( ) in allprojects of build . gradle
bat ` files should always have Windows - style newlines
Added changes to changelog
add execution permission to " input " script
Remove files from obolete and unused figures
Added oraclejdk8 and openjdk8 to the set of CI JDKs
updated gradle build tools version
Add project files to .
Updated CHANGES . txt
started core project
LPS - 56271 ConfigurationImpl clearCache is not resetting loaded _properties
add uaa classpath to eclipse classpath
Add missing override attribute .
added gitignore .
add site as a submodule
Ignore OSX and IDE files
Set oss parent to 9
learning git
upgrade okhttp 3 . 1 . 2 - > 3 . 2 . 0
Fix xhdpi box
update doc
fix up test case
Added auto unit testing
comment out snapshot plugin for release
ignoring eclipse files
Upgrade rxnetty version to 0 . 3 . 13
added checkstyle file info
Moving to a proper maven source directory
add newline to end of rules file .
Fix a dangling label .
Remove autolink form comment TextView
Removed ci . build = true
Updated API in README
Prepare change log .
add info about " Android - AppMsg - Gradle - Sample " in README . md
Delete lvtea0105
Removes lib / from top level
added scripts to create heron - tools self extracting binary
remove fiel
added Kasper to list of developers
Write checkstyle to stdout .
Fix travis error
Renaming pom artifact - id , so that gocd shows up instead of main ; when opening up multiple projects in idea .
Not using any more
Move META - INF / plugin .
Restored @ since javadoc tag of Convertible
remove use of deprecated property on Test
revert committed configuration
Add travis file to continous integration
Disable mocking " promise " in OSS Jest tests
add execution permission to " input " script
Remove redundant entries .
add context accessor for subclasses
added travis - ci config
changed publishJavadoc task from Copy to Sync
avoid nexus username and password on normal build
prepare release checkstyle - 6 . 11 . 2
Making default Socket timeout 20s ( from 8s ) .
Write checkstyle to stdout .
Revert parts of the .
Remove a spurious symlink
Add Application class .
Fix style on build . gradle
Upgrade version library to 1 . 1 . 0
Index Update Settings API does not update settings in real time , closes # 1807 .
build make buildlog include tests run and fail stacktraces
Delete build . gradle
updated version
Add getOnFocusChangeListener to View
Excluded testNg until Gradle migration is ready .
Add missing villager sounds .
Gradle required 2048 heap for multidex
added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration .
ignore intelliJ files
Reduce the amount of logging from the Javadoc plugin .
Setting build group and version
remove unnecessary config properties
Add maven central repo to readme
Fix floating point exception in emulator
update druid
Missed import
learning git
Putting tests in correct location
update joda - time to 2 . 8
Correct a typo .
udpated the read me
Remove unnecessary code
update wiki - snapshot
Reduce the amount of logging from the Javadoc plugin .
added phonegap icon to demo2
add jamm - 0 . 2 . 5 .
adjusting changes . txt
Include lib / instead of libs /
Removed DS_Store files
Bumped version to 5 . 0 . 0 - alpha4
fix build for example project
added intellij specific file to .
Delete a local ref in getSurface
Added missing JNA jar
update to latest android iconics - core
Remove jre6 redist
Remove circleci config
added package . html
Resized header
Set minSdkVersion + targetSdkVersion via build . gradle
Fixed WorldEditPlayer . findFreePosition ( ) ( / unstuck ) moving players up when the player was not stuck .
adding build and lib folder while ignoring their contents .
build make buildlog include tests run and fail stacktraces
added gitignore to blob
Updated Ant jar
Remove setting applicationId from library configuration
Added files via upload
update capture gif
Fix travis compilation
update factory images
updated distribution . xml to include whirr recipes and configuration files .
Ignore patterns
Give a useful error message when the neo4j shell script gets no command
fix some bug . . . . . . 123
Fix the build
Reverts removal of @ JsonIgnore on Event . type field
Fix typo in build file
upgraded guava to 20
Adding sample pages to web - service
update maven - release - plugin to 2 . 5 ( fixes issue where release fails to tag properly )
Delete obsolete icon
Fixed CCE ( EA - 38206 ) .
Add travis status badge to README .
Added a gitignore
Set version of gpg plugin .
gradle should output the stacktrace for test failures
LPS - 56049 Set default project group
ignore mac finder droppings
Only show warnings and errors from maven - javadoc - plugin
Add a META - INF / services file specifying JimfsFileSystemProvider as a service provider .
optimized imports
Removed unused import
Finish removal of pages submodule
Ignore IntelliJ IDEA files
Fix build script for generating md5s
Add Eclipse ' s bin / folder to .
Set bg and fg colour in site . css
Use Java 7 on AppVeyor
remove PIDFILE at stop time
Delete truth jar which I forgot to delete when removing Ant support .
Delete default README
Updated build . gradle for maven
add intelliJ files to gitignore
Created tech - debt entries for all components and laboratory components .
Fix un - updated rule change
added brew upgrade to MacOSX build instructions to avoid boost error .
Updated dslv submodule
add html attribute
ignore properties )
Updated project . proerties to build with latest SDK .
Prepare next development stage
Remove local testing file
Adds travis - ci configuration
Fixing transitive - ness of provided
Fixed overflow rounded icon in xxhdpi
added example images of thumbnails
fix bug
changed license name
Delete build . gradle
Bumped version
don ' t set the application title in the library
added example images of thumbnails
ignore all classpath / target / .
Bump readme version
Rename COPYING file to LICENSE
remove warning
remove blank line
Fix release number
Eradicate whitelisting
add JSR 305 annotations jar
Added 16x16 icon
add rm
Add fatter divider on xhdpi devices .
update javadoc
add iframe option
Avoid infinite loop
using bash specific syntax , so should declare rith shebang . . .
Updated gitignore to ignore hprof files
Added support for automatic legend generation for Wheelchair renderer
Remove AppState from Known Issues page
prepare for next development iteration
Not using any more
Fix typo .
Add transition screenshots
Remove obsolete file
Added a id to thumbnail + maincontent layout
Change game category image .
Setting default name for multi - project
Remove unused import
Added Travis
Added 5 new biomes as included in MC 1 . 1 as part of # BUKKIT - 496
Bumped version to 1 . 5 . 0 .
Put maven central back
Add pointer to h2o - 3 repo .
Use the correct language code for Korean
Fix mistype
Add files via upload
Ignore OSX and IDE files
Require Maven 3 . 1 . 1 or above
Fix travis config , again
added a test case for GremlinEngine . . . Going to probably rename these to GremlinScriptEngine and GremlinScriptEngineFactory to be consistent with other ScriptEngine classes .
Fixed incorrect value for ChatColor . BLACK ( was 1 , should be 0 )
Removed unnecessary @ SuppressWarnings
remove uneccessary whitespace .
remove bin directory
Add checkstyle plugin to lifecycle mapping exception to get things work without warnings on Kepler .
removed unnecessary import
Bump gherkin
Add file local variables to build . xml
Add feilaoda as contributor
ignore " bin " directory ( created by Eclipse )
Add Travis Build
Adding hero image .
Make 1 . 0 . 0 header the same level as others ( # 2885 )
Upgrade ZkClient to 0 . 8
remove swp file
Fix travis
Add notification icon for use with Android 1 . 5
updating astyanax version to 2 . 0 from 2 . 0 - beta
Missing Icon files .
Update SpongeCommon for chunk unload optimization .
add execution permission to " input " script
commented out a failing line
prepare for next development iteration
Added a gitignore
Properly handle empty layout in getFirstVisiblePosition ( )
Removed android - support - v4 . jar .
Add Eclipse files to .
Removed Merriweather light variation assets ( since they won ' t be used )
Revert " Make sure .
Move test data file to correct location .
add a - d flag to dpkg
Ignore a png file that ' s a documentation build artifact .
Added AppCompat & RecyclerView libraries
Added bin / to ignored files for Eclipse users
Upgrade Apache Commons Collections to v3 . 2 . 2
Removed new lines
Update doc commit pointer for 0 . 3 . 2 release
Add gitignore
removed querydsl - scala / .
Added example .
Rename COPYING file to LICENSE
Added symbols . macosx .
Remove unknown app module
Remove a spurious symlink
Bump readme version
reset version for development
Add dependency - reduced - pom . xml in .
Set travis jdk to java8
Add break line
Fix bug 3425610 Adjust Lock sound level
Add missing README link to Sonatype snapshot repo .
Generate XML reports from JUnit test reports
Add gitignore
Publish gradle - logging artifacts
bump up 1 . 1 . 0
Add missing import to chapter six example
Add service graphs
Removing legacy dependencies
Copy the XML descriptors .
add Travis CI configurations .
Add product flavor to reduce build time on debugging
Fix build
added screenshots
updated version number
Moving STUN sources from Openfire codebase to plugin .
Remove unused constant from TWLayoutManager
mention 5950 in NEWS
updated version
Adding hero image .
LRQA - 16067 Add list of product names into test . properties
add screenshot
Create img
add gitignore
update apk
add function with zero arguments
Add # include < sys / socket .
changed a typo from SHNAPSHOT to SNAPSHOT = )
Disable cobertura travis portion ( # 3122 )
Adding getaways . png asset
Update travis config
add readme for sample app
updated jar
Fix android_media_AudioSystem_getMasterMute return type .
added circle . yml
prepare for next development iteration
rename dir
Use the Cache for ~ / .
updated version
Add State and InputStream to the IRecognizer interface
remove empty file
delete README
Moved logging configuration to the PC Facade where it belongs .
Upgraded the version of gradle to 1 . 9 .
Updated sample , 0 . 8 . 4 . 0
Add local . properties to gitignore
Putting tests in correct location
missing colon
Change the flowdock notification for Travis builds .
Set animation to null after canceling current anim .
Updated CHANGES . txt
adding shim . R to description
Ignore bin and gen
Add project_config to sdk module
removing dangling directory
Updated library name
Add vim swp files to gitignore .
