set device_title type t VARCHAR ( 255 )
run manage . py as __main__
Add RIL_REQUEST_SET_INITIAL_ATTACH_APN .
Simplify range check for audio_mode_t ( continued )
Add MEDIA_PROJECTION_SERVICE to the ServiceName list .
hibernate validator jar in GRAILS_HOME so hibernate plugin doesn ' t get resolve errors on load
Remove dead variable _hdfsActive .
Remove tez_smb_1 from tests .
remove runit_NOPASS_nfoldextractor .
update vertical_stepview .
Bumped nebuladotNetflixoss from 2 . 2 . 3 to 2 . 2 . 5
Make PhoneAccount . CAPABILITY_VIDEO_CALLING public
Revert " Revert " Add PLAY and PAUSE keycodes and remove PLAY_PAUSE keycode . "
Javac ( at least for 1 . 7 . 0_51 on Mac ) wants fully qualified class name
Bump pegasus to 1 . 8 . 2 to get ' comma in batch_get ids ' fix out
Modify install_fbthrift .
Initialize audio quality with NONE instead of AMR_WB .
Fix typo in after_success maven command .
Upgrade dependency to maps from _r2 to _r3 .
Send ACTION_DEVICE_POLICY_MANAGER_STATE_CHANGED Broadcast when a user restriction has been changed .
Updated app_konference .
forgot appending & # NO_ISSUE
allow dots in hostnames ; ) # NO_ISSUES
Remove tez_smb_1 from tests .
Exclude pulling in netty from org . jbossdotNetty group ( # 664 )
java 1 . 4 . 2_08 , also includes non - european language support
Rename _large test to _medium after speedup .
Expose AtmosphereRequest ' s internal _request field
LOG_ASSERT needs a message .
Add test_metrics .
Add support for the Firebird database - Fixed CURRENT_USER ( )
Replaces libjnopus . so with a version which does not require GLIBC_2 . 14
Fix symbol prefix for ffi_closure_SYSV_inner on Darwin .
Add indices . requests . cache . clean_interval as a known settings
Move README . md to user_manual .
Fix android_media_AudioSystem_getMasterMute return type .
remove src / libs / gant_groovy1 . 8 - 1 . 9 . 4 - SNAPSHOT . jar
Changed min_adapter_stack to < =
Rename demo_4 .
Drop unused ic_launcher - web . png .
Add test_uuid .
Add jacoco_build .
added icons for shop = vending_machine and shop = alcohol
Add Truth 0 . 28 binary to third_party
avoid copying launch_minecraft_in_background . py into the zip .
remove MAX_TRANSFERS from RepeatedRaptorProfileRouter ( not used ) .
Delete color_demo .
Revert " Restored ic_dialog_menu_generic asset . "
Regenerate _collections skeleton for Mac ( PY - 2292 )
Added LOG_FILE_NAME .
Delete ic_launcher .
bump cqlsh ' s DEFAULT_CQLVER to 3 . 1 . 6
