add index on messageContentHeader
fixed PY - 6543 Django manage . py commands not working
Add new RIL command for sending ack to solicited async and unsolicited msg .
add a disconnect from ANativeWindow
Expose NETWORK_SCORE_SERVICE as @ SystemApi .
added missing hibernate commons annotations jar
Prevents unnecessary exception from GA failure .
Move local_mapred_error_cache .
remove runit_NOPASS_Rdoc_prcomp .
Replace demo7 . gif
Move to nebuladotNetflixoss 2 . 2 . 5
Remove TODO in TelecomManager .
Add PLAY and PAUSE keycodes and remove PLAY_PAUSE keycode .
Fix unnecessarily non - static inner class to static inner
Bump versions for release of pegasus 1 . 9 . 1
Modify install_mongodb .
Include code when converting unknown causes to string
remove extra - from maven arg
Reverted pom to r2 since our build server can ' t handle r3
Still return a package suspsended dialog if there is no owner .
replace app_konference .
Add missing JAVA_CMD variable to radioctl .
fix messagespread route # NO_ISSUE
Move local_mapred_error_cache .
Temporarily exclude parquet dependency , due to size , until it ' s needed
updated jre 1 . 4 . 2_12 for windows
Add large suffix .
Fix broken streaming impl
Fix uninitialized variable
Adding a ' .
Add support for the Firebird database - Fixed multi - record INSERT
Replaces the Opus libraries with ones linked against a lower version of glibc ( so that they run on debian , for example )
Add missing UNWIND entry ; disables .
assign success variable a value
rename file so its title has a space in it
Fix android_media_AudioSystem_getMasterMute return type .
Refactored quartz plugin .
Fix null top view crash
fixed git ignore name
remove obsolete drawable
Add data to trigger mismatch between train and test categorical levels .
Add jacoco_build .
Added fake large icons
Add truth - 0 . 27 . jar to third_party / truth .
add overlay
Making default Socket timeout 20s ( from 8s ) .
Delete demo2 . gif
Remove assets which are no longer used .
add table of contents in python / README
Added missing early_stopping arg from glm r wrapper .
Delete ic_launcher .
bump cqlsh ' s DEFAULT_CQLVER to 3 . 1 . 6
